/****************************************************************************
**
** Metadata for DTControl generated by dumpcpp from type library
** DTControl.tlb
**
****************************************************************************/

#define QAX_DUMPCPP_DTCONTROL_NOINLINES
#include "dtcontrol.h"

using namespace DTControl;

struct qt_meta_stringdata_all_t {
    QByteArrayData data[353];
    char stringdata0[4433];
};
#define QT_MOC_LITERAL(idx, ofs, len, table) \
    Q_STATIC_BYTE_ARRAY_DATA_HEADER_INITIALIZER_WITH_OFFSET(len, \
    offsetof(qt_meta_stringdata_all_t, stringdata##table) + ofs \
        - idx * sizeof(QByteArrayData) \
    )
static const qt_meta_stringdata_all_t qt_meta_stringdata_all = {
    {
QT_MOC_LITERAL(0, 0, 28, 0),
QT_MOC_LITERAL(1, 29, 17, 0),
QT_MOC_LITERAL(2, 47, 24, 0),
QT_MOC_LITERAL(3, 72, 11, 0),
QT_MOC_LITERAL(4, 84, 17, 0),
QT_MOC_LITERAL(5, 102, 9, 0),
QT_MOC_LITERAL(6, 112, 0, 0),
QT_MOC_LITERAL(7, 113, 6, 0),
QT_MOC_LITERAL(8, 120, 11, 0),
QT_MOC_LITERAL(9, 132, 5, 0),
QT_MOC_LITERAL(10, 138, 11, 0),
QT_MOC_LITERAL(11, 150, 8, 0),
QT_MOC_LITERAL(12, 159, 9, 0),
QT_MOC_LITERAL(13, 169, 4, 0),
QT_MOC_LITERAL(14, 174, 6, 0),
QT_MOC_LITERAL(15, 181, 4, 0),
QT_MOC_LITERAL(16, 186, 4, 0),
QT_MOC_LITERAL(17, 191, 15, 0),
QT_MOC_LITERAL(18, 207, 4, 0),
QT_MOC_LITERAL(19, 212, 6, 0),
QT_MOC_LITERAL(20, 219, 4, 0),
QT_MOC_LITERAL(21, 224, 4, 0),
QT_MOC_LITERAL(22, 229, 7, 0),
QT_MOC_LITERAL(23, 237, 7, 0),
QT_MOC_LITERAL(24, 245, 4, 0),
QT_MOC_LITERAL(25, 250, 9, 0),
QT_MOC_LITERAL(26, 260, 7, 0),
QT_MOC_LITERAL(27, 268, 4, 0),
QT_MOC_LITERAL(28, 273, 11, 0),
QT_MOC_LITERAL(29, 285, 12, 0),
QT_MOC_LITERAL(30, 298, 9, 0),
QT_MOC_LITERAL(31, 308, 28, 0),
QT_MOC_LITERAL(32, 337, 7, 0),
QT_MOC_LITERAL(33, 345, 24, 0),
QT_MOC_LITERAL(34, 370, 13, 0),
QT_MOC_LITERAL(35, 384, 5, 0),
QT_MOC_LITERAL(36, 390, 4, 0),
QT_MOC_LITERAL(37, 395, 8, 0),
QT_MOC_LITERAL(38, 404, 8, 0),
QT_MOC_LITERAL(39, 413, 12, 0),
QT_MOC_LITERAL(40, 426, 24, 0),
QT_MOC_LITERAL(41, 451, 22, 0),
QT_MOC_LITERAL(42, 474, 18, 0),
QT_MOC_LITERAL(43, 493, 11, 0),
QT_MOC_LITERAL(44, 505, 7, 0),
QT_MOC_LITERAL(45, 513, 7, 0),
QT_MOC_LITERAL(46, 521, 9, 0),
QT_MOC_LITERAL(47, 531, 7, 0),
QT_MOC_LITERAL(48, 539, 6, 0),
QT_MOC_LITERAL(49, 546, 5, 0),
QT_MOC_LITERAL(50, 552, 4, 0),
QT_MOC_LITERAL(51, 557, 11, 0),
QT_MOC_LITERAL(52, 569, 5, 0),
QT_MOC_LITERAL(53, 575, 8, 0),
QT_MOC_LITERAL(54, 584, 6, 0),
QT_MOC_LITERAL(55, 591, 11, 0),
QT_MOC_LITERAL(56, 603, 7, 0),
QT_MOC_LITERAL(57, 611, 9, 0),
QT_MOC_LITERAL(58, 621, 12, 0),
QT_MOC_LITERAL(59, 634, 4, 0),
QT_MOC_LITERAL(60, 639, 3, 0),
QT_MOC_LITERAL(61, 643, 3, 0),
QT_MOC_LITERAL(62, 647, 11, 0),
QT_MOC_LITERAL(63, 659, 8, 0),
QT_MOC_LITERAL(64, 668, 14, 0),
QT_MOC_LITERAL(65, 683, 11, 0),
QT_MOC_LITERAL(66, 695, 10, 0),
QT_MOC_LITERAL(67, 706, 7, 0),
QT_MOC_LITERAL(68, 714, 13, 0),
QT_MOC_LITERAL(69, 728, 10, 0),
QT_MOC_LITERAL(70, 739, 12, 0),
QT_MOC_LITERAL(71, 752, 9, 0),
QT_MOC_LITERAL(72, 762, 13, 0),
QT_MOC_LITERAL(73, 776, 10, 0),
QT_MOC_LITERAL(74, 787, 10, 0),
QT_MOC_LITERAL(75, 798, 7, 0),
QT_MOC_LITERAL(76, 806, 9, 0),
QT_MOC_LITERAL(77, 816, 9, 0),
QT_MOC_LITERAL(78, 826, 8, 0),
QT_MOC_LITERAL(79, 835, 14, 0),
QT_MOC_LITERAL(80, 850, 7, 0),
QT_MOC_LITERAL(81, 858, 8, 0),
QT_MOC_LITERAL(82, 867, 9, 0),
QT_MOC_LITERAL(83, 877, 22, 0),
QT_MOC_LITERAL(84, 900, 25, 0),
QT_MOC_LITERAL(85, 926, 21, 0),
QT_MOC_LITERAL(86, 948, 14, 0),
QT_MOC_LITERAL(87, 963, 5, 0),
QT_MOC_LITERAL(88, 969, 4, 0),
QT_MOC_LITERAL(89, 974, 10, 0),
QT_MOC_LITERAL(90, 985, 4, 0),
QT_MOC_LITERAL(91, 990, 8, 0),
QT_MOC_LITERAL(92, 999, 16, 0),
QT_MOC_LITERAL(93, 1016, 10, 0),
QT_MOC_LITERAL(94, 1027, 18, 0),
QT_MOC_LITERAL(95, 1046, 19, 0),
QT_MOC_LITERAL(96, 1066, 15, 0),
QT_MOC_LITERAL(97, 1082, 10, 0),
QT_MOC_LITERAL(98, 1093, 10, 0),
QT_MOC_LITERAL(99, 1104, 8, 0),
QT_MOC_LITERAL(100, 1113, 11, 0),
QT_MOC_LITERAL(101, 1125, 6, 0),
QT_MOC_LITERAL(102, 1132, 22, 0),
QT_MOC_LITERAL(103, 1155, 24, 0),
QT_MOC_LITERAL(104, 1180, 9, 0),
QT_MOC_LITERAL(105, 1190, 11, 0),
QT_MOC_LITERAL(106, 1202, 15, 0),
QT_MOC_LITERAL(107, 1218, 17, 0),
QT_MOC_LITERAL(108, 1236, 8, 0),
QT_MOC_LITERAL(109, 1245, 14, 0),
QT_MOC_LITERAL(110, 1260, 10, 0),
QT_MOC_LITERAL(111, 1271, 16, 0),
QT_MOC_LITERAL(112, 1288, 18, 0),
QT_MOC_LITERAL(113, 1307, 18, 0),
QT_MOC_LITERAL(114, 1326, 7, 0),
QT_MOC_LITERAL(115, 1334, 12, 0),
QT_MOC_LITERAL(116, 1347, 9, 0),
QT_MOC_LITERAL(117, 1357, 16, 0),
QT_MOC_LITERAL(118, 1374, 13, 0),
QT_MOC_LITERAL(119, 1388, 11, 0),
QT_MOC_LITERAL(120, 1400, 8, 0),
QT_MOC_LITERAL(121, 1409, 3, 0),
QT_MOC_LITERAL(122, 1413, 21, 0),
QT_MOC_LITERAL(123, 1435, 18, 0),
QT_MOC_LITERAL(124, 1454, 17, 0),
QT_MOC_LITERAL(125, 1472, 14, 0),
QT_MOC_LITERAL(126, 1487, 19, 0),
QT_MOC_LITERAL(127, 1507, 16, 0),
QT_MOC_LITERAL(128, 1524, 19, 0),
QT_MOC_LITERAL(129, 1544, 16, 0),
QT_MOC_LITERAL(130, 1561, 14, 0),
QT_MOC_LITERAL(131, 1576, 7, 0),
QT_MOC_LITERAL(132, 1584, 14, 0),
QT_MOC_LITERAL(133, 1599, 11, 0),
QT_MOC_LITERAL(134, 1611, 18, 0),
QT_MOC_LITERAL(135, 1630, 15, 0),
QT_MOC_LITERAL(136, 1646, 18, 0),
QT_MOC_LITERAL(137, 1665, 15, 0),
QT_MOC_LITERAL(138, 1681, 17, 0),
QT_MOC_LITERAL(139, 1699, 14, 0),
QT_MOC_LITERAL(140, 1714, 16, 0),
QT_MOC_LITERAL(141, 1731, 13, 0),
QT_MOC_LITERAL(142, 1745, 11, 0),
QT_MOC_LITERAL(143, 1757, 22, 0),
QT_MOC_LITERAL(144, 1780, 19, 0),
QT_MOC_LITERAL(145, 1800, 11, 0),
QT_MOC_LITERAL(146, 1812, 8, 0),
QT_MOC_LITERAL(147, 1821, 15, 0),
QT_MOC_LITERAL(148, 1837, 12, 0),
QT_MOC_LITERAL(149, 1850, 15, 0),
QT_MOC_LITERAL(150, 1866, 12, 0),
QT_MOC_LITERAL(151, 1879, 7, 0),
QT_MOC_LITERAL(152, 1887, 14, 0),
QT_MOC_LITERAL(153, 1902, 11, 0),
QT_MOC_LITERAL(154, 1914, 18, 0),
QT_MOC_LITERAL(155, 1933, 15, 0),
QT_MOC_LITERAL(156, 1949, 18, 0),
QT_MOC_LITERAL(157, 1968, 15, 0),
QT_MOC_LITERAL(158, 1984, 15, 0),
QT_MOC_LITERAL(159, 2000, 12, 0),
QT_MOC_LITERAL(160, 2013, 14, 0),
QT_MOC_LITERAL(161, 2028, 11, 0),
QT_MOC_LITERAL(162, 2040, 21, 0),
QT_MOC_LITERAL(163, 2062, 18, 0),
QT_MOC_LITERAL(164, 2081, 28, 0),
QT_MOC_LITERAL(165, 2110, 25, 0),
QT_MOC_LITERAL(166, 2136, 9, 0),
QT_MOC_LITERAL(167, 2146, 16, 0),
QT_MOC_LITERAL(168, 2163, 13, 0),
QT_MOC_LITERAL(169, 2177, 13, 0),
QT_MOC_LITERAL(170, 2191, 10, 0),
QT_MOC_LITERAL(171, 2202, 14, 0),
QT_MOC_LITERAL(172, 2217, 11, 0),
QT_MOC_LITERAL(173, 2229, 17, 0),
QT_MOC_LITERAL(174, 2247, 14, 0),
QT_MOC_LITERAL(175, 2262, 17, 0),
QT_MOC_LITERAL(176, 2280, 14, 0),
QT_MOC_LITERAL(177, 2295, 19, 0),
QT_MOC_LITERAL(178, 2315, 16, 0),
QT_MOC_LITERAL(179, 2332, 21, 0),
QT_MOC_LITERAL(180, 2354, 13, 0),
QT_MOC_LITERAL(181, 2368, 11, 0),
QT_MOC_LITERAL(182, 2380, 8, 0),
QT_MOC_LITERAL(183, 2389, 11, 0),
QT_MOC_LITERAL(184, 2401, 18, 0),
QT_MOC_LITERAL(185, 2420, 15, 0),
QT_MOC_LITERAL(186, 2436, 19, 0),
QT_MOC_LITERAL(187, 2456, 16, 0),
QT_MOC_LITERAL(188, 2473, 8, 0),
QT_MOC_LITERAL(189, 2482, 16, 0),
QT_MOC_LITERAL(190, 2499, 4, 0),
QT_MOC_LITERAL(191, 2504, 4, 0),
QT_MOC_LITERAL(192, 2509, 14, 0),
QT_MOC_LITERAL(193, 2524, 14, 0),
QT_MOC_LITERAL(194, 2539, 21, 0),
QT_MOC_LITERAL(195, 2561, 18, 0),
QT_MOC_LITERAL(196, 2580, 14, 0),
QT_MOC_LITERAL(197, 2595, 11, 0),
QT_MOC_LITERAL(198, 2607, 10, 0),
QT_MOC_LITERAL(199, 2618, 16, 0),
QT_MOC_LITERAL(200, 2635, 14, 0),
QT_MOC_LITERAL(201, 2650, 21, 0),
QT_MOC_LITERAL(202, 2672, 18, 0),
QT_MOC_LITERAL(203, 2691, 10, 0),
QT_MOC_LITERAL(204, 2702, 6, 0),
QT_MOC_LITERAL(205, 2709, 10, 0),
QT_MOC_LITERAL(206, 2720, 12, 0),
QT_MOC_LITERAL(207, 2733, 11, 0),
QT_MOC_LITERAL(208, 2745, 10, 0),
QT_MOC_LITERAL(209, 2756, 10, 0),
QT_MOC_LITERAL(210, 2767, 17, 0),
QT_MOC_LITERAL(211, 2785, 10, 0),
QT_MOC_LITERAL(212, 2796, 14, 0),
QT_MOC_LITERAL(213, 2811, 11, 0),
QT_MOC_LITERAL(214, 2823, 9, 0),
QT_MOC_LITERAL(215, 2833, 12, 0),
QT_MOC_LITERAL(216, 2846, 11, 0),
QT_MOC_LITERAL(217, 2858, 25, 0),
QT_MOC_LITERAL(218, 2884, 23, 0),
QT_MOC_LITERAL(219, 2908, 12, 0),
QT_MOC_LITERAL(220, 2921, 10, 0),
QT_MOC_LITERAL(221, 2932, 4, 0),
QT_MOC_LITERAL(222, 2937, 6, 0),
QT_MOC_LITERAL(223, 2944, 4, 0),
QT_MOC_LITERAL(224, 2949, 6, 0),
QT_MOC_LITERAL(225, 2956, 4, 0),
QT_MOC_LITERAL(226, 2961, 8, 0),
QT_MOC_LITERAL(227, 2970, 7, 0),
QT_MOC_LITERAL(228, 2978, 6, 0),
QT_MOC_LITERAL(229, 2985, 13, 0),
QT_MOC_LITERAL(230, 2999, 7, 0),
QT_MOC_LITERAL(231, 3007, 12, 0),
QT_MOC_LITERAL(232, 3020, 12, 0),
QT_MOC_LITERAL(233, 3033, 5, 0),
QT_MOC_LITERAL(234, 3039, 5, 0),
QT_MOC_LITERAL(235, 3045, 16, 0),
QT_MOC_LITERAL(236, 3062, 9, 0),
QT_MOC_LITERAL(237, 3072, 5, 0),
QT_MOC_LITERAL(238, 3078, 6, 0),
QT_MOC_LITERAL(239, 3085, 13, 0),
QT_MOC_LITERAL(240, 3099, 5, 0),
QT_MOC_LITERAL(241, 3105, 1, 0),
QT_MOC_LITERAL(242, 3107, 1, 0),
QT_MOC_LITERAL(243, 3109, 10, 0),
QT_MOC_LITERAL(244, 3120, 6, 0),
QT_MOC_LITERAL(245, 3127, 6, 0),
QT_MOC_LITERAL(246, 3134, 8, 0),
QT_MOC_LITERAL(247, 3143, 19, 0),
QT_MOC_LITERAL(248, 3163, 16, 0),
QT_MOC_LITERAL(249, 3180, 8, 0),
QT_MOC_LITERAL(250, 3189, 8, 0),
QT_MOC_LITERAL(251, 3198, 8, 0),
QT_MOC_LITERAL(252, 3207, 8, 0),
QT_MOC_LITERAL(253, 3216, 10, 0),
QT_MOC_LITERAL(254, 3227, 8, 0),
QT_MOC_LITERAL(255, 3236, 8, 0),
QT_MOC_LITERAL(256, 3245, 8, 0),
QT_MOC_LITERAL(257, 3254, 10, 0),
QT_MOC_LITERAL(258, 3265, 23, 0),
QT_MOC_LITERAL(259, 3289, 19, 0),
QT_MOC_LITERAL(260, 3309, 15, 0),
QT_MOC_LITERAL(261, 3325, 8, 0),
QT_MOC_LITERAL(262, 3334, 8, 0),
QT_MOC_LITERAL(263, 3343, 11, 0),
QT_MOC_LITERAL(264, 3355, 10, 0),
QT_MOC_LITERAL(265, 3366, 8, 0),
QT_MOC_LITERAL(266, 3375, 12, 0),
QT_MOC_LITERAL(267, 3388, 11, 0),
QT_MOC_LITERAL(268, 3400, 13, 0),
QT_MOC_LITERAL(269, 3414, 14, 0),
QT_MOC_LITERAL(270, 3429, 9, 0),
QT_MOC_LITERAL(271, 3439, 10, 0),
QT_MOC_LITERAL(272, 3450, 4, 0),
QT_MOC_LITERAL(273, 3455, 8, 0),
QT_MOC_LITERAL(274, 3464, 4, 0),
QT_MOC_LITERAL(275, 3469, 8, 0),
QT_MOC_LITERAL(276, 3478, 16, 0),
QT_MOC_LITERAL(277, 3495, 12, 0),
QT_MOC_LITERAL(278, 3508, 9, 0),
QT_MOC_LITERAL(279, 3518, 17, 0),
QT_MOC_LITERAL(280, 3536, 14, 0),
QT_MOC_LITERAL(281, 3551, 17, 0),
QT_MOC_LITERAL(282, 3569, 14, 0),
QT_MOC_LITERAL(283, 3584, 11, 0),
QT_MOC_LITERAL(284, 3596, 8, 0),
QT_MOC_LITERAL(285, 3605, 12, 0),
QT_MOC_LITERAL(286, 3618, 9, 0),
QT_MOC_LITERAL(287, 3628, 12, 0),
QT_MOC_LITERAL(288, 3641, 9, 0),
QT_MOC_LITERAL(289, 3651, 11, 0),
QT_MOC_LITERAL(290, 3663, 8, 0),
QT_MOC_LITERAL(291, 3672, 8, 0),
QT_MOC_LITERAL(292, 3681, 5, 0),
QT_MOC_LITERAL(293, 3687, 8, 0),
QT_MOC_LITERAL(294, 3696, 5, 0),
QT_MOC_LITERAL(295, 3702, 9, 0),
QT_MOC_LITERAL(296, 3712, 6, 0),
QT_MOC_LITERAL(297, 3719, 9, 0),
QT_MOC_LITERAL(298, 3729, 6, 0),
QT_MOC_LITERAL(299, 3736, 22, 0),
QT_MOC_LITERAL(300, 3759, 19, 0),
QT_MOC_LITERAL(301, 3779, 17, 0),
QT_MOC_LITERAL(302, 3797, 14, 0),
QT_MOC_LITERAL(303, 3812, 10, 0),
QT_MOC_LITERAL(304, 3823, 7, 0),
QT_MOC_LITERAL(305, 3831, 4, 0),
QT_MOC_LITERAL(306, 3836, 15, 0),
QT_MOC_LITERAL(307, 3852, 13, 0),
QT_MOC_LITERAL(308, 3866, 9, 0),
QT_MOC_LITERAL(309, 3876, 11, 0),
QT_MOC_LITERAL(310, 3888, 13, 0),
QT_MOC_LITERAL(311, 3902, 9, 0),
QT_MOC_LITERAL(312, 3912, 11, 0),
QT_MOC_LITERAL(313, 3924, 11, 0),
QT_MOC_LITERAL(314, 3936, 9, 0),
QT_MOC_LITERAL(315, 3946, 19, 0),
QT_MOC_LITERAL(316, 3966, 21, 0),
QT_MOC_LITERAL(317, 3988, 17, 0),
QT_MOC_LITERAL(318, 4006, 10, 0),
QT_MOC_LITERAL(319, 4017, 11, 0),
QT_MOC_LITERAL(320, 4029, 5, 0),
QT_MOC_LITERAL(321, 4035, 4, 0),
QT_MOC_LITERAL(322, 4040, 13, 0),
QT_MOC_LITERAL(323, 4054, 10, 0),
QT_MOC_LITERAL(324, 4065, 17, 0),
QT_MOC_LITERAL(325, 4083, 14, 0),
QT_MOC_LITERAL(326, 4098, 15, 0),
QT_MOC_LITERAL(327, 4114, 12, 0),
QT_MOC_LITERAL(328, 4127, 8, 0),
QT_MOC_LITERAL(329, 4136, 14, 0),
QT_MOC_LITERAL(330, 4151, 11, 0),
QT_MOC_LITERAL(331, 4163, 15, 0),
QT_MOC_LITERAL(332, 4179, 12, 0),
QT_MOC_LITERAL(333, 4192, 9, 0),
QT_MOC_LITERAL(334, 4202, 6, 0),
QT_MOC_LITERAL(335, 4209, 11, 0),
QT_MOC_LITERAL(336, 4221, 8, 0),
QT_MOC_LITERAL(337, 4230, 13, 0),
QT_MOC_LITERAL(338, 4244, 10, 0),
QT_MOC_LITERAL(339, 4255, 13, 0),
QT_MOC_LITERAL(340, 4269, 10, 0),
QT_MOC_LITERAL(341, 4280, 14, 0),
QT_MOC_LITERAL(342, 4295, 11, 0),
QT_MOC_LITERAL(343, 4307, 14, 0),
QT_MOC_LITERAL(344, 4322, 11, 0),
QT_MOC_LITERAL(345, 4334, 21, 0),
QT_MOC_LITERAL(346, 4356, 17, 0),
QT_MOC_LITERAL(347, 4374, 6, 0),
QT_MOC_LITERAL(348, 4381, 9, 0),
QT_MOC_LITERAL(349, 4391, 3, 0),
QT_MOC_LITERAL(350, 4395, 10, 0),
QT_MOC_LITERAL(351, 4406, 7, 0),
QT_MOC_LITERAL(352, 4414, 17, 0)
    },
    "DTControl::CDTDisplayControl\0Event Interface 1\0_IDTDisplayControlEvents\0"
    "Interface 0\0IDTDisplayControl\0EndChange\0\0EndPos\0GammaChange\0Gamma\0StartChange\0"
    "StartPos\0exception\0code\0source\0disc\0help\0propertyChanged\0name\0signal\0argc\0"
    "argv\0Refresh\0SetBits\0Bits\0SetEndPos\0SetGama\0Gama\0SetStartPos\0ObjectHandle\0"
    "IUnknown*\0DTControl::IDTDisplayControl\0control\0DTControl::CDTClockMeter\0"
    "IDTClockMeter\0Start\0Stop\0CPUClock\0CostInNs\0CurrentClock\0DTControl::IDTClockMeter\0"
    "DTControl::CDTDetector\0_IDTDetectorEvents\0IDTDetector\0DTError\0ErrorID\0ErrorInfo\0"
    "OnClose\0OnOpen\0Close\0Open\0PrintErrMsg\0ErrID\0QString&\0ErrMsg\0SendCommand\0"
    "bstrCmd\0bstrRTMsg\0SendCommandA\0int&\0Cmd\0pRT\0SetBaudRate\0BaudRate\0SetChannelType\0"
    "ChannelType\0SetCmdPort\0CmdPort\0SetCmdTimeOut\0CmdTimeOut\0SetIPAddress\0IPAddress\0"
    "SetSerialPort\0SerialPort\0SetUsbPort\0UsbPort\0StartPing\0nInterval\0StopPing\0"
    "DCULineTrigger\0IsLUGAS\0IsOpened\0LastErrID\0DTControl::IDTDetector\0"
    "DTControl::CDTCommanderF3\0_IDTCommanderF3Events\0IDTCommanderF3\0Index\0Gain\0"
    "Initialize\0Mode\0LoadGain\0LoadGainFromDisk\0LoadOffset\0LoadOffsetFromDisk\0"
    "OffBoardCalibration\0CalibrationType\0pImgObject\0StartPixel\0EndPixel\0TargetValue\0"
    "Offset\0OnBoardGainCalibration\0OnBoardOffsetCalibration\0ResetGain\0ResetOffset\0"
    "RetrieveSysinfo\0SaveCurrentStatus\0SaveGain\0SaveGainToDisk\0SaveOffset\0"
    "SaveOffsetToDisk\0SendExFrameTrigger\0SensitivityLevelLG\0channel\0SetASIC_Type\0"
    "ASIC_Type\0SetAverageFilter\0AverageFilter\0SetBaseline\0Baseline\0rhs\0"
    "SetCorrectionBaseline\0CorrectionBaseline\0SetCorrectionGain\0CorrectionGain\0"
    "SetCorrectionOffset\0CorrectionOffset\0SetDM_AverageFilter\0DM_AverageFilter\0"
    "SetDM_TestMode\0Address\0SetDataPattern\0DataPattern\0SetDataPatternMode\0"
    "DataPatternMode\0SetDelay_SweepMode\0Delay_SweepMode\0SetDetectorObject\0"
    "DetectorObject\0SetDetector_Type\0Detector_Type\0SetEndPixel\0SetExFrameTriggerDelay\0"
    "ExFrameTriggerDelay\0SetFrameOut\0FrameOut\0SetFrameTrigger\0FrameTrigger\0"
    "SetFrame_Source\0Frame_Source\0SetGain\0SetIF_TestMode\0IF_TestMode\0SetImageOutputType\0"
    "ImageOutputType\0SetIntegrationTime\0IntegrationTime\0SetLinac_Source\0Linac_Source\0"
    "SetLineTrigger\0LineTrigger\0SetMovingOffsetFilter\0MovingOffsetFilter\0"
    "SetNoContinueIntegrationTime\0NoContinueIntegrationTime\0SetOffset\0SetOperationMode\0"
    "OperationMode\0SetOutputBits\0OutputBits\0SetOverallGain\0OverallGain\0SetPixelMovingAvg\0"
    "PixelMovingAvg\0SetSHTriggerDelay\0SHTriggerDelay\0SetSensitivityLevel\0"
    "SensitivityLevel\0SetSensitivityLevelLG\0SetStartPixel\0SetSumLines\0SumLines\0"
    "SetTestMode\0SetTestPulseNumber\0TestPulseNumber\0SetTrigger_RawDelay\0"
    "Trigger_RawDelay\0TestMode\0WriteDataPattern\0Base\0Step\0get_ModuleGain\0"
    "load_ASIC_Type\0load_DM_AverageFilter\0load_Detector_Type\0put_ModuleGain\0"
    "ModuleIndex\0EnergyMode\0SensitivityValue\0save_ASIC_Type\0save_DM_AverageFilter\0"
    "save_Detector_Type\0FECardsNum\0FEMode\0FPGA_Build\0FPGA_Version\0MCU_Version\0"
    "MaxIntTime\0MinIntTime\0ModuleSensitivity\0ModuleType\0ModuleTypeName\0PixelNumber\0"
    "PixelSize\0SerialNumber\0Temperature\0DTControl::IDTCommanderF3\0DTControl::CImageObject\0"
    "IImageObject\0ColAverage\0pAvg\0ColMax\0pMax\0ColMin\0pMin\0ColNoise\0double&\0pNoise\0"
    "DoStatistical\0CalType\0FinalRelease\0GetImageData\0uint&\0pData\0ImageLineAddress\0"
    "LineIndex\0Width\0Height\0BytesPerPixel\0Pixel\0X\0Y\0RowAverage\0RowMax\0RowMin\0"
    "RowNoise\0SetImageDataAddress\0ImageDataAddress\0SetPixel\0VBColAvg\0VBColMax\0"
    "VBColMin\0VBColNoise\0VBRowAvg\0VBRowMax\0VBRowMin\0VBRowNoise\0DTControl::IImageObject\0"
    "DTControl::CDTImage\0_IDTImageEvents\0IDTImage\0Datalost\0LostlineNum\0FrameReady\0"
    "NumLines\0OnImageClose\0OnImageOpen\0SubFrameReady\0NumOfBlockLeft\0StartLine\0"
    "bLastBlock\0Grab\0FrameNum\0Save\0FilePath\0SetBytesPerPixel\0SetDebugMode\0DebugMode\0"
    "SetDualEnergyMode\0DualEnergyMode\0SetExFrameTrigger\0ExFrameTrigger\0SetFileName\0"
    "FileName\0SetImagePort\0ImagePort\0SetImgHeight\0ImgHeight\0SetImgWidth\0ImgWidth\0"
    "SetROI_X\0ROI_X\0SetROI_Y\0ROI_Y\0SetROI_dx\0ROI_dx\0SetROI_dy\0ROI_dy\0"
    "SetStreamPixelPerBytes\0StreamPixelPerBytes\0SetSubFrameHeight\0SubFrameHeight\0"
    "SetTimeOut\0TimeOut\0Snap\0StartGrabEngine\0TrigerOneGrab\0BandWidth\0ImageObject\0"
    "IImageObject*\0IsGrabing\0LostStartID\0ROI_DTImage\0IDTImage*\0DTControl::IDTImage\0"
    "DTControl::CDTDisplay\0_IDTDisplayEvents\0IDTDisplay\0DTMouseMove\0Value\0Load\0"
    "SetDataSource\0DataSource\0SetDisplayControl\0DisplayControl\0SetDisplayScale\0"
    "DisplayScale\0SetGamma\0SetInfoDisplay\0InfoDisplay\0SetMapDirection\0MapDirection\0"
    "SetMapEnd\0MapEnd\0SetMapStart\0MapStart\0SetOrgPoint_X\0OrgPoint_X\0SetOrgPoint_Y\0"
    "OrgPoint_Y\0SetRefreshMode\0RefreshMode\0SetRefreshRate\0RefreshRate\0"
    "DTControl::IDTDisplay\0DTControl::CDTLog\0IDTLog\0LogString\0Msg\0SetLogMode\0"
    "LogMode\0DTControl::IDTLog\0"
};
#undef QT_MOC_LITERAL

static const uint qt_meta_data_DTControl__CDTDisplayControl[] = {

 // content:
    7, // revision
    0,  // classname
    2, 14, // classinfo
    11, 18, // methods
    5, 114, // properties
    0, 0, // enums/sets
    0, 0, // constructors
    0, // flags
    6, // signal count

 // classinfo: key, value
    1, 2, 
    3, 4, 

// signal: name, argc, parameters, tag, flags
    5, 1, 73, 6, 5,
    8, 1, 76, 6, 5,
    10, 1, 79, 6, 5,
    12, 4, 82, 6, 5,
    17, 1, 91, 6, 5,
    19, 3, 94, 6, 5,

// slot: name, argc, parameters, tag, flags
    22, 0, 101, 6, 9,
    23, 1, 102, 6, 9,
    25, 1, 105, 6, 9,
    26, 1, 108, 6, 9,
    28, 1, 111, 6, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, 7,
    QMetaType::Void, QMetaType::Double, 9,
    QMetaType::Void, QMetaType::Int, 11,
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 13, 14, 15, 16,
    QMetaType::Void, QMetaType::QString, 18,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 18, 20, 21,

// slot: parameters
    QMetaType::Void,
    QMetaType::Void, QMetaType::Int, 24,
    QMetaType::Void, QMetaType::Int, 7,
    QMetaType::Void, QMetaType::Double, 27,
    QMetaType::Void, QMetaType::Int, 11,

 // properties: name, type, flags
    24, QMetaType::Int, 0x02015003, 		 // int Bits
    7, QMetaType::Int, 0x02015003, 		 // int EndPos
    27, QMetaType::Double, 0x06015003, 		 // double Gama
    29, 0x80000000 | 30, 0x00005001, 		 // IUnknown* ObjectHandle
    11, QMetaType::Int, 0x02015003, 		 // int StartPos

    0 // eod
};

const QMetaObject CDTDisplayControl::staticMetaObject = {
{ &QWidget::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_DTControl__CDTDisplayControl, 0, 0, 0 }
};

void *CDTDisplayControl::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "DTControl::CDTDisplayControl"))
        return static_cast<void*>(const_cast<CDTDisplayControl*>(this));
    return QAxWidget::qt_metacast(_clname);
}
static const uint qt_meta_data_DTControl__IDTDisplayControl[] = {

 // content:
    7, // revision
    31,  // classname
    0, 0, // classinfo
    8, 14, // methods
    6, 86, // properties
    0, 0, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

// signal: name, argc, parameters, tag, flags
    12, 4, 54, 6, 5,
    17, 1, 63, 6, 5,
    19, 3, 66, 6, 5,

// slot: name, argc, parameters, tag, flags
    22, 0, 73, 6, 9,
    23, 1, 74, 6, 9,
    25, 1, 77, 6, 9,
    26, 1, 80, 6, 9,
    28, 1, 83, 6, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 13, 14, 15, 16,
    QMetaType::Void, QMetaType::QString, 18,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 18, 20, 21,

// slot: parameters
    QMetaType::Void,
    QMetaType::Void, QMetaType::Int, 24,
    QMetaType::Void, QMetaType::Int, 7,
    QMetaType::Void, QMetaType::Double, 27,
    QMetaType::Void, QMetaType::Int, 11,

 // properties: name, type, flags
    24, QMetaType::Int, 0x02015003, 		 // int Bits
    7, QMetaType::Int, 0x02015003, 		 // int EndPos
    27, QMetaType::Double, 0x06015003, 		 // double Gama
    29, 0x80000000 | 30, 0x00005001, 		 // IUnknown* ObjectHandle
    11, QMetaType::Int, 0x02015003, 		 // int StartPos
    32, QMetaType::QString, 0x0a055003, 		 // QString control

    0 // eod
};

const QMetaObject IDTDisplayControl::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_DTControl__IDTDisplayControl, 0, 0, 0 }
};

void *IDTDisplayControl::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "DTControl::IDTDisplayControl"))
        return static_cast<void*>(const_cast<IDTDisplayControl*>(this));
    return QAxObject::qt_metacast(_clname);
}
static const uint qt_meta_data_DTControl__CDTClockMeter[] = {

 // content:
    7, // revision
    33,  // classname
    1, 14, // classinfo
    5, 16, // methods
    3, 62, // properties
    0, 0, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

 // classinfo: key, value
    3, 34, 

// signal: name, argc, parameters, tag, flags
    12, 4, 41, 6, 5,
    17, 1, 50, 6, 5,
    19, 3, 53, 6, 5,

// slot: name, argc, parameters, tag, flags
    35, 0, 60, 6, 9,
    36, 0, 61, 6, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 13, 14, 15, 16,
    QMetaType::Void, QMetaType::QString, 18,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 18, 20, 21,

// slot: parameters
    QMetaType::Void,
    QMetaType::Void,

 // properties: name, type, flags
    37, QMetaType::Double, 0x06005001, 		 // double CPUClock
    38, QMetaType::Int, 0x02005001, 		 // int CostInNs
    39, QMetaType::Int, 0x02005001, 		 // int CurrentClock

    0 // eod
};

const QMetaObject CDTClockMeter::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_DTControl__CDTClockMeter, 0, 0, 0 }
};

void *CDTClockMeter::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "DTControl::CDTClockMeter"))
        return static_cast<void*>(const_cast<CDTClockMeter*>(this));
    return QAxObject::qt_metacast(_clname);
}
static const uint qt_meta_data_DTControl__IDTClockMeter[] = {

 // content:
    7, // revision
    40,  // classname
    0, 0, // classinfo
    5, 14, // methods
    4, 60, // properties
    0, 0, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

// signal: name, argc, parameters, tag, flags
    12, 4, 39, 6, 5,
    17, 1, 48, 6, 5,
    19, 3, 51, 6, 5,

// slot: name, argc, parameters, tag, flags
    35, 0, 58, 6, 9,
    36, 0, 59, 6, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 13, 14, 15, 16,
    QMetaType::Void, QMetaType::QString, 18,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 18, 20, 21,

// slot: parameters
    QMetaType::Void,
    QMetaType::Void,

 // properties: name, type, flags
    37, QMetaType::Double, 0x06005001, 		 // double CPUClock
    38, QMetaType::Int, 0x02005001, 		 // int CostInNs
    39, QMetaType::Int, 0x02005001, 		 // int CurrentClock
    32, QMetaType::QString, 0x0a055003, 		 // QString control

    0 // eod
};

const QMetaObject IDTClockMeter::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_DTControl__IDTClockMeter, 0, 0, 0 }
};

void *IDTClockMeter::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "DTControl::IDTClockMeter"))
        return static_cast<void*>(const_cast<IDTClockMeter*>(this));
    return QAxObject::qt_metacast(_clname);
}
static const uint qt_meta_data_DTControl__CDTDetector[] = {

 // content:
    7, // revision
    41,  // classname
    2, 14, // classinfo
    20, 18, // methods
    12, 186, // properties
    0, 0, // enums/sets
    0, 0, // constructors
    0, // flags
    6, // signal count

 // classinfo: key, value
    1, 42, 
    3, 43, 

// signal: name, argc, parameters, tag, flags
    44, 2, 118, 6, 5,
    47, 0, 123, 6, 5,
    48, 0, 124, 6, 5,
    12, 4, 125, 6, 5,
    17, 1, 134, 6, 5,
    19, 3, 137, 6, 5,

// slot: name, argc, parameters, tag, flags
    49, 0, 144, 6, 9,
    50, 0, 145, 6, 9,
    51, 2, 146, 6, 9,
    55, 2, 151, 6, 9,
    58, 2, 156, 6, 9,
    62, 1, 161, 6, 9,
    64, 1, 164, 6, 9,
    66, 1, 167, 6, 9,
    68, 1, 170, 6, 9,
    70, 1, 173, 6, 9,
    72, 1, 176, 6, 9,
    74, 1, 179, 6, 9,
    76, 1, 182, 6, 9,
    78, 0, 185, 6, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, 45, 46,
    QMetaType::Void,
    QMetaType::Void,
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 13, 14, 15, 16,
    QMetaType::Void, QMetaType::QString, 18,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 18, 20, 21,

// slot: parameters
    QMetaType::Void,
    QMetaType::Int,
    QMetaType::Void, QMetaType::Int, 0x80000000 | 53, 52, 54,
    QMetaType::Int, QMetaType::QString, 0x80000000 | 53, 56, 57,
    QMetaType::Int, 0x80000000 | 59, 0x80000000 | 59, 60, 61,
    QMetaType::Void, QMetaType::Int, 63,
    QMetaType::Void, QMetaType::Int, 65,
    QMetaType::Void, QMetaType::Int, 67,
    QMetaType::Void, QMetaType::Int, 69,
    QMetaType::Void, QMetaType::QString, 71,
    QMetaType::Void, QMetaType::Int, 73,
    QMetaType::Void, QMetaType::Int, 75,
    QMetaType::Void, QMetaType::Int, 77,
    QMetaType::Void,

 // properties: name, type, flags
    63, QMetaType::Int, 0x02015003, 		 // int BaudRate
    65, QMetaType::Int, 0x02015003, 		 // int ChannelType
    67, QMetaType::Int, 0x02015003, 		 // int CmdPort
    69, QMetaType::Int, 0x02015003, 		 // int CmdTimeOut
    79, QMetaType::Int, 0x02005001, 		 // int DCULineTrigger
    71, QMetaType::QString, 0x0a015003, 		 // QString IPAddress
    80, QMetaType::Int, 0x02005001, 		 // int IsLUGAS
    81, QMetaType::Int, 0x02005001, 		 // int IsOpened
    82, QMetaType::Int, 0x02005001, 		 // int LastErrID
    29, 0x80000000 | 30, 0x00005001, 		 // IUnknown* ObjectHandle
    73, QMetaType::Int, 0x02015003, 		 // int SerialPort
    75, QMetaType::Int, 0x02015003, 		 // int UsbPort

    0 // eod
};

const QMetaObject CDTDetector::staticMetaObject = {
{ &QWidget::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_DTControl__CDTDetector, 0, 0, 0 }
};

void *CDTDetector::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "DTControl::CDTDetector"))
        return static_cast<void*>(const_cast<CDTDetector*>(this));
    return QAxWidget::qt_metacast(_clname);
}
static const uint qt_meta_data_DTControl__IDTDetector[] = {

 // content:
    7, // revision
    83,  // classname
    0, 0, // classinfo
    17, 14, // methods
    13, 160, // properties
    0, 0, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

// signal: name, argc, parameters, tag, flags
    12, 4, 99, 6, 5,
    17, 1, 108, 6, 5,
    19, 3, 111, 6, 5,

// slot: name, argc, parameters, tag, flags
    49, 0, 118, 6, 9,
    50, 0, 119, 6, 9,
    51, 2, 120, 6, 9,
    55, 2, 125, 6, 9,
    58, 2, 130, 6, 9,
    62, 1, 135, 6, 9,
    64, 1, 138, 6, 9,
    66, 1, 141, 6, 9,
    68, 1, 144, 6, 9,
    70, 1, 147, 6, 9,
    72, 1, 150, 6, 9,
    74, 1, 153, 6, 9,
    76, 1, 156, 6, 9,
    78, 0, 159, 6, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 13, 14, 15, 16,
    QMetaType::Void, QMetaType::QString, 18,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 18, 20, 21,

// slot: parameters
    QMetaType::Void,
    QMetaType::Int,
    QMetaType::Void, QMetaType::Int, 0x80000000 | 53, 52, 54,
    QMetaType::Int, QMetaType::QString, 0x80000000 | 53, 56, 57,
    QMetaType::Int, 0x80000000 | 59, 0x80000000 | 59, 60, 61,
    QMetaType::Void, QMetaType::Int, 63,
    QMetaType::Void, QMetaType::Int, 65,
    QMetaType::Void, QMetaType::Int, 67,
    QMetaType::Void, QMetaType::Int, 69,
    QMetaType::Void, QMetaType::QString, 71,
    QMetaType::Void, QMetaType::Int, 73,
    QMetaType::Void, QMetaType::Int, 75,
    QMetaType::Void, QMetaType::Int, 77,
    QMetaType::Void,

 // properties: name, type, flags
    63, QMetaType::Int, 0x02015003, 		 // int BaudRate
    65, QMetaType::Int, 0x02015003, 		 // int ChannelType
    67, QMetaType::Int, 0x02015003, 		 // int CmdPort
    69, QMetaType::Int, 0x02015003, 		 // int CmdTimeOut
    79, QMetaType::Int, 0x02005001, 		 // int DCULineTrigger
    71, QMetaType::QString, 0x0a015003, 		 // QString IPAddress
    80, QMetaType::Int, 0x02005001, 		 // int IsLUGAS
    81, QMetaType::Int, 0x02005001, 		 // int IsOpened
    82, QMetaType::Int, 0x02005001, 		 // int LastErrID
    29, 0x80000000 | 30, 0x00005001, 		 // IUnknown* ObjectHandle
    73, QMetaType::Int, 0x02015003, 		 // int SerialPort
    75, QMetaType::Int, 0x02015003, 		 // int UsbPort
    32, QMetaType::QString, 0x0a055003, 		 // QString control

    0 // eod
};

const QMetaObject IDTDetector::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_DTControl__IDTDetector, 0, 0, 0 }
};

void *IDTDetector::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "DTControl::IDTDetector"))
        return static_cast<void*>(const_cast<IDTDetector*>(this));
    return QAxObject::qt_metacast(_clname);
}
static const uint qt_meta_data_DTControl__CDTCommanderF3[] = {

 // content:
    7, // revision
    84,  // classname
    2, 14, // classinfo
    74, 18, // methods
    49, 608, // properties
    0, 0, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

 // classinfo: key, value
    1, 85, 
    3, 86, 

// signal: name, argc, parameters, tag, flags
    12, 4, 388, 6, 5,
    17, 1, 397, 6, 5,
    19, 3, 400, 6, 5,

// slot: name, argc, parameters, tag, flags
    65, 1, 407, 6, 9,
    88, 1, 410, 6, 9,
    89, 1, 413, 6, 9,
    91, 1, 416, 6, 9,
    92, 0, 419, 6, 9,
    93, 0, 420, 6, 9,
    94, 0, 421, 6, 9,
    95, 5, 422, 6, 9,
    101, 1, 433, 6, 9,
    102, 1, 436, 6, 9,
    103, 0, 439, 6, 9,
    104, 0, 440, 6, 9,
    105, 0, 441, 6, 9,
    106, 0, 442, 6, 9,
    107, 0, 443, 6, 9,
    108, 1, 444, 6, 9,
    109, 0, 447, 6, 9,
    110, 0, 448, 6, 9,
    111, 0, 449, 6, 9,
    112, 0, 450, 6, 9,
    113, 1, 451, 6, 9,
    115, 1, 454, 6, 9,
    117, 1, 457, 6, 9,
    119, 1, 460, 6, 9,
    64, 2, 463, 6, 9,
    122, 1, 468, 6, 9,
    124, 1, 471, 6, 9,
    126, 1, 474, 6, 9,
    128, 1, 477, 6, 9,
    130, 2, 480, 6, 9,
    132, 1, 485, 6, 9,
    134, 1, 488, 6, 9,
    136, 1, 491, 6, 9,
    138, 1, 494, 6, 9,
    140, 1, 497, 6, 9,
    142, 1, 500, 6, 9,
    143, 1, 503, 6, 9,
    145, 1, 506, 6, 9,
    147, 1, 509, 6, 9,
    149, 1, 512, 6, 9,
    151, 2, 515, 6, 9,
    152, 1, 520, 6, 9,
    154, 1, 523, 6, 9,
    156, 1, 526, 6, 9,
    158, 1, 529, 6, 9,
    160, 1, 532, 6, 9,
    162, 1, 535, 6, 9,
    164, 1, 538, 6, 9,
    166, 2, 541, 6, 9,
    167, 1, 546, 6, 9,
    169, 1, 549, 6, 9,
    171, 1, 552, 6, 9,
    173, 1, 555, 6, 9,
    175, 1, 558, 6, 9,
    177, 1, 561, 6, 9,
    179, 2, 564, 6, 9,
    180, 1, 569, 6, 9,
    181, 1, 572, 6, 9,
    183, 2, 575, 6, 9,
    184, 1, 580, 6, 9,
    186, 1, 583, 6, 9,
    188, 1, 586, 6, 9,
    189, 2, 589, 6, 9,
    192, 0, 594, 6, 9,
    193, 0, 595, 6, 9,
    194, 0, 596, 6, 9,
    195, 0, 597, 6, 9,
    196, 3, 598, 6, 9,
    200, 0, 605, 6, 9,
    201, 0, 606, 6, 9,
    202, 0, 607, 6, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 13, 14, 15, 16,
    QMetaType::Void, QMetaType::QString, 18,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 18, 20, 21,

// slot: parameters
    QMetaType::Int, QMetaType::Int, 87,
    QMetaType::Double, QMetaType::Int, 87,
    QMetaType::Void, QMetaType::Int, 90,
    QMetaType::Void, QMetaType::Int, 87,
    QMetaType::Int,
    QMetaType::Void,
    QMetaType::Int,
    QMetaType::Void, QMetaType::Int, 0x80000000 | 30, QMetaType::Int, QMetaType::Int, QMetaType::Int, 96, 97, 98, 99, 100,
    QMetaType::Int, QMetaType::Int, 87,
    QMetaType::Void, QMetaType::Int, 100,
    QMetaType::Void,
    QMetaType::Void,
    QMetaType::Void,
    QMetaType::Void,
    QMetaType::Void,
    QMetaType::Void, QMetaType::Int, 87,
    QMetaType::Int,
    QMetaType::Void,
    QMetaType::Int,
    QMetaType::Void,
    QMetaType::Int, QMetaType::Int, 114,
    QMetaType::Void, QMetaType::Int, 116,
    QMetaType::Void, QMetaType::Int, 118,
    QMetaType::Void, QMetaType::Int, 120,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, 87, 121,
    QMetaType::Void, QMetaType::Int, 123,
    QMetaType::Void, QMetaType::Int, 125,
    QMetaType::Void, QMetaType::Int, 127,
    QMetaType::Void, QMetaType::Int, 129,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, 131, 121,
    QMetaType::Void, QMetaType::Int, 133,
    QMetaType::Void, QMetaType::Int, 135,
    QMetaType::Void, QMetaType::Int, 137,
    QMetaType::Void, 0x80000000 | 30, 139,
    QMetaType::Void, QMetaType::Int, 141,
    QMetaType::Void, QMetaType::Int, 99,
    QMetaType::Void, QMetaType::Int, 144,
    QMetaType::Void, QMetaType::Int, 146,
    QMetaType::Void, QMetaType::Int, 148,
    QMetaType::Void, QMetaType::Int, 150,
    QMetaType::Void, QMetaType::Int, QMetaType::Double, 87, 121,
    QMetaType::Void, QMetaType::Int, 153,
    QMetaType::Void, QMetaType::Int, 155,
    QMetaType::Void, QMetaType::Int, 157,
    QMetaType::Void, QMetaType::Int, 159,
    QMetaType::Void, QMetaType::Int, 161,
    QMetaType::Void, QMetaType::Int, 163,
    QMetaType::Void, QMetaType::Int, 165,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, 87, 121,
    QMetaType::Void, QMetaType::Int, 168,
    QMetaType::Void, QMetaType::Int, 170,
    QMetaType::Void, QMetaType::Double, 172,
    QMetaType::Void, QMetaType::Int, 174,
    QMetaType::Void, QMetaType::Int, 176,
    QMetaType::Void, QMetaType::Int, 178,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, 114, 121,
    QMetaType::Void, QMetaType::Int, 98,
    QMetaType::Void, QMetaType::Int, 182,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, 131, 121,
    QMetaType::Void, QMetaType::Int, 185,
    QMetaType::Void, QMetaType::Int, 187,
    QMetaType::Int, QMetaType::Int, 131,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, 190, 191,
    QMetaType::Int,
    QMetaType::Void,
    QMetaType::Void,
    QMetaType::Void,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, QMetaType::Int, 197, 198, 199,
    QMetaType::Void,
    QMetaType::Void,
    QMetaType::Void,

 // properties: name, type, flags
    116, QMetaType::Int, 0x02015003, 		 // int ASIC_Type
    118, QMetaType::Int, 0x02015003, 		 // int AverageFilter
    120, QMetaType::Int, 0x02015003, 		 // int Baseline
    123, QMetaType::Int, 0x02015003, 		 // int CorrectionBaseline
    125, QMetaType::Int, 0x02015003, 		 // int CorrectionGain
    127, QMetaType::Int, 0x02015003, 		 // int CorrectionOffset
    129, QMetaType::Int, 0x02015003, 		 // int DM_AverageFilter
    133, QMetaType::Int, 0x02015003, 		 // int DataPattern
    135, QMetaType::Int, 0x02015003, 		 // int DataPatternMode
    137, QMetaType::Int, 0x02015003, 		 // int Delay_SweepMode
    139, 0x80000000 | 30, 0x00015003, 		 // IUnknown* DetectorObject
    141, QMetaType::Int, 0x02015003, 		 // int Detector_Type
    99, QMetaType::Int, 0x02015003, 		 // int EndPixel
    144, QMetaType::Int, 0x02015003, 		 // int ExFrameTriggerDelay
    203, QMetaType::Int, 0x02005001, 		 // int FECardsNum
    204, QMetaType::Int, 0x02005001, 		 // int FEMode
    205, QMetaType::Int, 0x02005001, 		 // int FPGA_Build
    206, QMetaType::Int, 0x02005001, 		 // int FPGA_Version
    146, QMetaType::Int, 0x02015003, 		 // int FrameOut
    148, QMetaType::Int, 0x02015003, 		 // int FrameTrigger
    150, QMetaType::Int, 0x02015003, 		 // int Frame_Source
    153, QMetaType::Int, 0x02015003, 		 // int IF_TestMode
    155, QMetaType::Int, 0x02015003, 		 // int ImageOutputType
    157, QMetaType::Int, 0x02015003, 		 // int IntegrationTime
    81, QMetaType::Int, 0x02005001, 		 // int IsOpened
    159, QMetaType::Int, 0x02015003, 		 // int Linac_Source
    161, QMetaType::Int, 0x02015003, 		 // int LineTrigger
    207, QMetaType::Int, 0x02005001, 		 // int MCU_Version
    208, QMetaType::Int, 0x02005001, 		 // int MaxIntTime
    209, QMetaType::Int, 0x02005001, 		 // int MinIntTime
    210, QMetaType::Int, 0x02005001, 		 // int ModuleSensitivity
    211, QMetaType::Int, 0x02005001, 		 // int ModuleType
    212, QMetaType::QString, 0x0a005001, 		 // QString ModuleTypeName
    163, QMetaType::Int, 0x02015003, 		 // int MovingOffsetFilter
    165, QMetaType::Int, 0x02015003, 		 // int NoContinueIntegrationTime
    168, QMetaType::Int, 0x02015003, 		 // int OperationMode
    170, QMetaType::Int, 0x02015003, 		 // int OutputBits
    172, QMetaType::Double, 0x06015003, 		 // double OverallGain
    174, QMetaType::Int, 0x02015003, 		 // int PixelMovingAvg
    213, QMetaType::Int, 0x02005001, 		 // int PixelNumber
    214, QMetaType::Double, 0x06005001, 		 // double PixelSize
    176, QMetaType::Int, 0x02015003, 		 // int SHTriggerDelay
    178, QMetaType::Int, 0x02015003, 		 // int SensitivityLevel
    215, QMetaType::QString, 0x0a005001, 		 // QString SerialNumber
    98, QMetaType::Int, 0x02015003, 		 // int StartPixel
    182, QMetaType::Int, 0x02015003, 		 // int SumLines
    216, QMetaType::Int, 0x02005001, 		 // int Temperature
    185, QMetaType::Int, 0x02015003, 		 // int TestPulseNumber
    187, QMetaType::Int, 0x02015003, 		 // int Trigger_RawDelay

    0 // eod
};

const QMetaObject CDTCommanderF3::staticMetaObject = {
{ &QWidget::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_DTControl__CDTCommanderF3, 0, 0, 0 }
};

void *CDTCommanderF3::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "DTControl::CDTCommanderF3"))
        return static_cast<void*>(const_cast<CDTCommanderF3*>(this));
    return QAxWidget::qt_metacast(_clname);
}
static const uint qt_meta_data_DTControl__IDTCommanderF3[] = {

 // content:
    7, // revision
    217,  // classname
    0, 0, // classinfo
    74, 14, // methods
    50, 604, // properties
    0, 0, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

// signal: name, argc, parameters, tag, flags
    12, 4, 384, 6, 5,
    17, 1, 393, 6, 5,
    19, 3, 396, 6, 5,

// slot: name, argc, parameters, tag, flags
    65, 1, 403, 6, 9,
    88, 1, 406, 6, 9,
    89, 1, 409, 6, 9,
    91, 1, 412, 6, 9,
    92, 0, 415, 6, 9,
    93, 0, 416, 6, 9,
    94, 0, 417, 6, 9,
    95, 5, 418, 6, 9,
    101, 1, 429, 6, 9,
    102, 1, 432, 6, 9,
    103, 0, 435, 6, 9,
    104, 0, 436, 6, 9,
    105, 0, 437, 6, 9,
    106, 0, 438, 6, 9,
    107, 0, 439, 6, 9,
    108, 1, 440, 6, 9,
    109, 0, 443, 6, 9,
    110, 0, 444, 6, 9,
    111, 0, 445, 6, 9,
    112, 0, 446, 6, 9,
    113, 1, 447, 6, 9,
    115, 1, 450, 6, 9,
    117, 1, 453, 6, 9,
    119, 1, 456, 6, 9,
    64, 2, 459, 6, 9,
    122, 1, 464, 6, 9,
    124, 1, 467, 6, 9,
    126, 1, 470, 6, 9,
    128, 1, 473, 6, 9,
    130, 2, 476, 6, 9,
    132, 1, 481, 6, 9,
    134, 1, 484, 6, 9,
    136, 1, 487, 6, 9,
    138, 1, 490, 6, 9,
    140, 1, 493, 6, 9,
    142, 1, 496, 6, 9,
    143, 1, 499, 6, 9,
    145, 1, 502, 6, 9,
    147, 1, 505, 6, 9,
    149, 1, 508, 6, 9,
    151, 2, 511, 6, 9,
    152, 1, 516, 6, 9,
    154, 1, 519, 6, 9,
    156, 1, 522, 6, 9,
    158, 1, 525, 6, 9,
    160, 1, 528, 6, 9,
    162, 1, 531, 6, 9,
    164, 1, 534, 6, 9,
    166, 2, 537, 6, 9,
    167, 1, 542, 6, 9,
    169, 1, 545, 6, 9,
    171, 1, 548, 6, 9,
    173, 1, 551, 6, 9,
    175, 1, 554, 6, 9,
    177, 1, 557, 6, 9,
    179, 2, 560, 6, 9,
    180, 1, 565, 6, 9,
    181, 1, 568, 6, 9,
    183, 2, 571, 6, 9,
    184, 1, 576, 6, 9,
    186, 1, 579, 6, 9,
    188, 1, 582, 6, 9,
    189, 2, 585, 6, 9,
    192, 0, 590, 6, 9,
    193, 0, 591, 6, 9,
    194, 0, 592, 6, 9,
    195, 0, 593, 6, 9,
    196, 3, 594, 6, 9,
    200, 0, 601, 6, 9,
    201, 0, 602, 6, 9,
    202, 0, 603, 6, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 13, 14, 15, 16,
    QMetaType::Void, QMetaType::QString, 18,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 18, 20, 21,

// slot: parameters
    QMetaType::Int, QMetaType::Int, 87,
    QMetaType::Double, QMetaType::Int, 87,
    QMetaType::Void, QMetaType::Int, 90,
    QMetaType::Void, QMetaType::Int, 87,
    QMetaType::Int,
    QMetaType::Void,
    QMetaType::Int,
    QMetaType::Void, QMetaType::Int, 0x80000000 | 30, QMetaType::Int, QMetaType::Int, QMetaType::Int, 96, 97, 98, 99, 100,
    QMetaType::Int, QMetaType::Int, 87,
    QMetaType::Void, QMetaType::Int, 100,
    QMetaType::Void,
    QMetaType::Void,
    QMetaType::Void,
    QMetaType::Void,
    QMetaType::Void,
    QMetaType::Void, QMetaType::Int, 87,
    QMetaType::Int,
    QMetaType::Void,
    QMetaType::Int,
    QMetaType::Void,
    QMetaType::Int, QMetaType::Int, 114,
    QMetaType::Void, QMetaType::Int, 116,
    QMetaType::Void, QMetaType::Int, 118,
    QMetaType::Void, QMetaType::Int, 120,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, 87, 121,
    QMetaType::Void, QMetaType::Int, 123,
    QMetaType::Void, QMetaType::Int, 125,
    QMetaType::Void, QMetaType::Int, 127,
    QMetaType::Void, QMetaType::Int, 129,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, 131, 121,
    QMetaType::Void, QMetaType::Int, 133,
    QMetaType::Void, QMetaType::Int, 135,
    QMetaType::Void, QMetaType::Int, 137,
    QMetaType::Void, 0x80000000 | 30, 139,
    QMetaType::Void, QMetaType::Int, 141,
    QMetaType::Void, QMetaType::Int, 99,
    QMetaType::Void, QMetaType::Int, 144,
    QMetaType::Void, QMetaType::Int, 146,
    QMetaType::Void, QMetaType::Int, 148,
    QMetaType::Void, QMetaType::Int, 150,
    QMetaType::Void, QMetaType::Int, QMetaType::Double, 87, 121,
    QMetaType::Void, QMetaType::Int, 153,
    QMetaType::Void, QMetaType::Int, 155,
    QMetaType::Void, QMetaType::Int, 157,
    QMetaType::Void, QMetaType::Int, 159,
    QMetaType::Void, QMetaType::Int, 161,
    QMetaType::Void, QMetaType::Int, 163,
    QMetaType::Void, QMetaType::Int, 165,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, 87, 121,
    QMetaType::Void, QMetaType::Int, 168,
    QMetaType::Void, QMetaType::Int, 170,
    QMetaType::Void, QMetaType::Double, 172,
    QMetaType::Void, QMetaType::Int, 174,
    QMetaType::Void, QMetaType::Int, 176,
    QMetaType::Void, QMetaType::Int, 178,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, 114, 121,
    QMetaType::Void, QMetaType::Int, 98,
    QMetaType::Void, QMetaType::Int, 182,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, 131, 121,
    QMetaType::Void, QMetaType::Int, 185,
    QMetaType::Void, QMetaType::Int, 187,
    QMetaType::Int, QMetaType::Int, 131,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, 190, 191,
    QMetaType::Int,
    QMetaType::Void,
    QMetaType::Void,
    QMetaType::Void,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, QMetaType::Int, 197, 198, 199,
    QMetaType::Void,
    QMetaType::Void,
    QMetaType::Void,

 // properties: name, type, flags
    116, QMetaType::Int, 0x02015003, 		 // int ASIC_Type
    118, QMetaType::Int, 0x02015003, 		 // int AverageFilter
    120, QMetaType::Int, 0x02015003, 		 // int Baseline
    123, QMetaType::Int, 0x02015003, 		 // int CorrectionBaseline
    125, QMetaType::Int, 0x02015003, 		 // int CorrectionGain
    127, QMetaType::Int, 0x02015003, 		 // int CorrectionOffset
    129, QMetaType::Int, 0x02015003, 		 // int DM_AverageFilter
    133, QMetaType::Int, 0x02015003, 		 // int DataPattern
    135, QMetaType::Int, 0x02015003, 		 // int DataPatternMode
    137, QMetaType::Int, 0x02015003, 		 // int Delay_SweepMode
    139, 0x80000000 | 30, 0x00015003, 		 // IUnknown* DetectorObject
    141, QMetaType::Int, 0x02015003, 		 // int Detector_Type
    99, QMetaType::Int, 0x02015003, 		 // int EndPixel
    144, QMetaType::Int, 0x02015003, 		 // int ExFrameTriggerDelay
    203, QMetaType::Int, 0x02005001, 		 // int FECardsNum
    204, QMetaType::Int, 0x02005001, 		 // int FEMode
    205, QMetaType::Int, 0x02005001, 		 // int FPGA_Build
    206, QMetaType::Int, 0x02005001, 		 // int FPGA_Version
    146, QMetaType::Int, 0x02015003, 		 // int FrameOut
    148, QMetaType::Int, 0x02015003, 		 // int FrameTrigger
    150, QMetaType::Int, 0x02015003, 		 // int Frame_Source
    153, QMetaType::Int, 0x02015003, 		 // int IF_TestMode
    155, QMetaType::Int, 0x02015003, 		 // int ImageOutputType
    157, QMetaType::Int, 0x02015003, 		 // int IntegrationTime
    81, QMetaType::Int, 0x02005001, 		 // int IsOpened
    159, QMetaType::Int, 0x02015003, 		 // int Linac_Source
    161, QMetaType::Int, 0x02015003, 		 // int LineTrigger
    207, QMetaType::Int, 0x02005001, 		 // int MCU_Version
    208, QMetaType::Int, 0x02005001, 		 // int MaxIntTime
    209, QMetaType::Int, 0x02005001, 		 // int MinIntTime
    210, QMetaType::Int, 0x02005001, 		 // int ModuleSensitivity
    211, QMetaType::Int, 0x02005001, 		 // int ModuleType
    212, QMetaType::QString, 0x0a005001, 		 // QString ModuleTypeName
    163, QMetaType::Int, 0x02015003, 		 // int MovingOffsetFilter
    165, QMetaType::Int, 0x02015003, 		 // int NoContinueIntegrationTime
    168, QMetaType::Int, 0x02015003, 		 // int OperationMode
    170, QMetaType::Int, 0x02015003, 		 // int OutputBits
    172, QMetaType::Double, 0x06015003, 		 // double OverallGain
    174, QMetaType::Int, 0x02015003, 		 // int PixelMovingAvg
    213, QMetaType::Int, 0x02005001, 		 // int PixelNumber
    214, QMetaType::Double, 0x06005001, 		 // double PixelSize
    176, QMetaType::Int, 0x02015003, 		 // int SHTriggerDelay
    178, QMetaType::Int, 0x02015003, 		 // int SensitivityLevel
    215, QMetaType::QString, 0x0a005001, 		 // QString SerialNumber
    98, QMetaType::Int, 0x02015003, 		 // int StartPixel
    182, QMetaType::Int, 0x02015003, 		 // int SumLines
    216, QMetaType::Int, 0x02005001, 		 // int Temperature
    185, QMetaType::Int, 0x02015003, 		 // int TestPulseNumber
    187, QMetaType::Int, 0x02015003, 		 // int Trigger_RawDelay
    32, QMetaType::QString, 0x0a055003, 		 // QString control

    0 // eod
};

const QMetaObject IDTCommanderF3::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_DTControl__IDTCommanderF3, 0, 0, 0 }
};

void *IDTCommanderF3::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "DTControl::IDTCommanderF3"))
        return static_cast<void*>(const_cast<IDTCommanderF3*>(this));
    return QAxObject::qt_metacast(_clname);
}
static const uint qt_meta_data_DTControl__CImageObject[] = {

 // content:
    7, // revision
    218,  // classname
    1, 14, // classinfo
    27, 16, // methods
    4, 250, // properties
    0, 0, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

 // classinfo: key, value
    3, 219, 

// signal: name, argc, parameters, tag, flags
    12, 4, 151, 6, 5,
    17, 1, 160, 6, 5,
    19, 3, 163, 6, 5,

// slot: name, argc, parameters, tag, flags
    220, 1, 170, 6, 9,
    222, 1, 173, 6, 9,
    224, 1, 176, 6, 9,
    226, 1, 179, 6, 9,
    229, 1, 182, 6, 9,
    231, 0, 185, 6, 9,
    232, 1, 186, 6, 9,
    235, 1, 189, 6, 9,
    50, 3, 192, 6, 9,
    240, 2, 199, 6, 9,
    243, 1, 204, 6, 9,
    244, 1, 207, 6, 9,
    245, 1, 210, 6, 9,
    246, 1, 213, 6, 9,
    247, 1, 216, 6, 9,
    249, 3, 219, 6, 9,
    250, 1, 226, 6, 9,
    251, 1, 229, 6, 9,
    252, 1, 232, 6, 9,
    253, 1, 235, 6, 9,
    254, 1, 238, 6, 9,
    255, 1, 241, 6, 9,
    256, 1, 244, 6, 9,
    257, 1, 247, 6, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 13, 14, 15, 16,
    QMetaType::Void, QMetaType::QString, 18,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 18, 20, 21,

// slot: parameters
    QMetaType::Void, 0x80000000 | 59, 221,
    QMetaType::Void, 0x80000000 | 59, 223,
    QMetaType::Void, 0x80000000 | 59, 225,
    QMetaType::Void, 0x80000000 | 227, 228,
    QMetaType::Void, QMetaType::Int, 230,
    QMetaType::Void,
    QMetaType::Int, 0x80000000 | 233, 234,
    QMetaType::Int, QMetaType::Int, 236,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, QMetaType::Int, 237, 238, 239,
    QMetaType::Int, QMetaType::Int, QMetaType::Int, 241, 242,
    QMetaType::Void, 0x80000000 | 59, 221,
    QMetaType::Void, 0x80000000 | 59, 223,
    QMetaType::Void, 0x80000000 | 59, 225,
    QMetaType::Void, 0x80000000 | 227, 228,
    QMetaType::Void, QMetaType::Int, 248,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, QMetaType::Int, 241, 242, 121,
    QMetaType::Double, QMetaType::Int, 87,
    QMetaType::Double, QMetaType::Int, 87,
    QMetaType::Double, QMetaType::Int, 87,
    QMetaType::Double, QMetaType::Int, 87,
    QMetaType::Double, QMetaType::Int, 87,
    QMetaType::Double, QMetaType::Int, 87,
    QMetaType::Double, QMetaType::Int, 87,
    QMetaType::Double, QMetaType::Int, 87,

 // properties: name, type, flags
    239, QMetaType::Int, 0x02005001, 		 // int BytesPerPixel
    238, QMetaType::Int, 0x02005001, 		 // int Height
    248, QMetaType::Int, 0x02015003, 		 // int ImageDataAddress
    237, QMetaType::Int, 0x02005001, 		 // int Width

    0 // eod
};

const QMetaObject CImageObject::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_DTControl__CImageObject, 0, 0, 0 }
};

void *CImageObject::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "DTControl::CImageObject"))
        return static_cast<void*>(const_cast<CImageObject*>(this));
    return QAxObject::qt_metacast(_clname);
}
static const uint qt_meta_data_DTControl__IImageObject[] = {

 // content:
    7, // revision
    258,  // classname
    0, 0, // classinfo
    27, 14, // methods
    5, 248, // properties
    0, 0, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

// signal: name, argc, parameters, tag, flags
    12, 4, 149, 6, 5,
    17, 1, 158, 6, 5,
    19, 3, 161, 6, 5,

// slot: name, argc, parameters, tag, flags
    220, 1, 168, 6, 9,
    222, 1, 171, 6, 9,
    224, 1, 174, 6, 9,
    226, 1, 177, 6, 9,
    229, 1, 180, 6, 9,
    231, 0, 183, 6, 9,
    232, 1, 184, 6, 9,
    235, 1, 187, 6, 9,
    50, 3, 190, 6, 9,
    240, 2, 197, 6, 9,
    243, 1, 202, 6, 9,
    244, 1, 205, 6, 9,
    245, 1, 208, 6, 9,
    246, 1, 211, 6, 9,
    247, 1, 214, 6, 9,
    249, 3, 217, 6, 9,
    250, 1, 224, 6, 9,
    251, 1, 227, 6, 9,
    252, 1, 230, 6, 9,
    253, 1, 233, 6, 9,
    254, 1, 236, 6, 9,
    255, 1, 239, 6, 9,
    256, 1, 242, 6, 9,
    257, 1, 245, 6, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 13, 14, 15, 16,
    QMetaType::Void, QMetaType::QString, 18,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 18, 20, 21,

// slot: parameters
    QMetaType::Void, 0x80000000 | 59, 221,
    QMetaType::Void, 0x80000000 | 59, 223,
    QMetaType::Void, 0x80000000 | 59, 225,
    QMetaType::Void, 0x80000000 | 227, 228,
    QMetaType::Void, QMetaType::Int, 230,
    QMetaType::Void,
    QMetaType::Int, 0x80000000 | 233, 234,
    QMetaType::Int, QMetaType::Int, 236,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, QMetaType::Int, 237, 238, 239,
    QMetaType::Int, QMetaType::Int, QMetaType::Int, 241, 242,
    QMetaType::Void, 0x80000000 | 59, 221,
    QMetaType::Void, 0x80000000 | 59, 223,
    QMetaType::Void, 0x80000000 | 59, 225,
    QMetaType::Void, 0x80000000 | 227, 228,
    QMetaType::Void, QMetaType::Int, 248,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, QMetaType::Int, 241, 242, 121,
    QMetaType::Double, QMetaType::Int, 87,
    QMetaType::Double, QMetaType::Int, 87,
    QMetaType::Double, QMetaType::Int, 87,
    QMetaType::Double, QMetaType::Int, 87,
    QMetaType::Double, QMetaType::Int, 87,
    QMetaType::Double, QMetaType::Int, 87,
    QMetaType::Double, QMetaType::Int, 87,
    QMetaType::Double, QMetaType::Int, 87,

 // properties: name, type, flags
    239, QMetaType::Int, 0x02005001, 		 // int BytesPerPixel
    238, QMetaType::Int, 0x02005001, 		 // int Height
    248, QMetaType::Int, 0x02015003, 		 // int ImageDataAddress
    237, QMetaType::Int, 0x02005001, 		 // int Width
    32, QMetaType::QString, 0x0a055003, 		 // QString control

    0 // eod
};

const QMetaObject IImageObject::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_DTControl__IImageObject, 0, 0, 0 }
};

void *IImageObject::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "DTControl::IImageObject"))
        return static_cast<void*>(const_cast<IImageObject*>(this));
    return QAxObject::qt_metacast(_clname);
}
static const uint qt_meta_data_DTControl__CDTImage[] = {

 // content:
    7, // revision
    259,  // classname
    2, 14, // classinfo
    35, 18, // methods
    25, 304, // properties
    0, 0, // enums/sets
    0, 0, // constructors
    0, // flags
    9, // signal count

 // classinfo: key, value
    1, 260, 
    3, 261, 

// signal: name, argc, parameters, tag, flags
    44, 2, 193, 6, 5,
    262, 1, 198, 6, 5,
    264, 1, 201, 6, 5,
    266, 0, 204, 6, 5,
    267, 0, 205, 6, 5,
    268, 4, 206, 6, 5,
    12, 4, 215, 6, 5,
    17, 1, 224, 6, 5,
    19, 3, 227, 6, 5,

// slot: name, argc, parameters, tag, flags
    49, 0, 234, 6, 9,
    272, 1, 235, 6, 9,
    50, 0, 238, 6, 9,
    51, 2, 239, 6, 9,
    274, 1, 244, 6, 9,
    276, 1, 247, 6, 9,
    64, 1, 250, 6, 9,
    277, 1, 253, 6, 9,
    138, 1, 256, 6, 9,
    279, 1, 259, 6, 9,
    281, 1, 262, 6, 9,
    283, 1, 265, 6, 9,
    285, 1, 268, 6, 9,
    287, 1, 271, 6, 9,
    289, 1, 274, 6, 9,
    291, 1, 277, 6, 9,
    293, 1, 280, 6, 9,
    295, 1, 283, 6, 9,
    297, 1, 286, 6, 9,
    299, 1, 289, 6, 9,
    301, 1, 292, 6, 9,
    303, 1, 295, 6, 9,
    305, 1, 298, 6, 9,
    306, 0, 301, 6, 9,
    36, 0, 302, 6, 9,
    307, 0, 303, 6, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, 45, 46,
    QMetaType::Void, QMetaType::Int, 263,
    QMetaType::Void, QMetaType::Int, 265,
    QMetaType::Void,
    QMetaType::Void,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, 269, 270, 265, 271,
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 13, 14, 15, 16,
    QMetaType::Void, QMetaType::QString, 18,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 18, 20, 21,

// slot: parameters
    QMetaType::Void,
    QMetaType::Int, QMetaType::Int, 273,
    QMetaType::Int,
    QMetaType::Void, QMetaType::Int, 0x80000000 | 53, 52, 54,
    QMetaType::Void, QMetaType::QString, 275,
    QMetaType::Void, QMetaType::Int, 239,
    QMetaType::Void, QMetaType::Int, 65,
    QMetaType::Void, QMetaType::Int, 278,
    QMetaType::Void, 0x80000000 | 30, 139,
    QMetaType::Void, QMetaType::Int, 280,
    QMetaType::Void, QMetaType::Int, 282,
    QMetaType::Void, QMetaType::QString, 284,
    QMetaType::Void, QMetaType::Int, 286,
    QMetaType::Void, QMetaType::Int, 288,
    QMetaType::Void, QMetaType::Int, 290,
    QMetaType::Void, QMetaType::Int, 292,
    QMetaType::Void, QMetaType::Int, 294,
    QMetaType::Void, QMetaType::Int, 296,
    QMetaType::Void, QMetaType::Int, 298,
    QMetaType::Void, QMetaType::Int, 300,
    QMetaType::Void, QMetaType::Int, 302,
    QMetaType::Void, QMetaType::Int, 304,
    QMetaType::Int, QMetaType::Int, 273,
    QMetaType::Int,
    QMetaType::Void,
    QMetaType::Void,

 // properties: name, type, flags
    308, QMetaType::Int, 0x02005001, 		 // int BandWidth
    239, QMetaType::Int, 0x02015003, 		 // int BytesPerPixel
    65, QMetaType::Int, 0x02015003, 		 // int ChannelType
    278, QMetaType::Int, 0x02015003, 		 // int DebugMode
    139, 0x80000000 | 30, 0x00015003, 		 // IUnknown* DetectorObject
    280, QMetaType::Int, 0x02015003, 		 // int DualEnergyMode
    282, QMetaType::Int, 0x02015003, 		 // int ExFrameTrigger
    284, QMetaType::QString, 0x0a015003, 		 // QString FileName
    309, 0x80000000 | 310, 0x00005001, 		 // IImageObject* ImageObject
    286, QMetaType::Int, 0x02015003, 		 // int ImagePort
    288, QMetaType::Int, 0x02015003, 		 // int ImgHeight
    290, QMetaType::Int, 0x02015003, 		 // int ImgWidth
    311, QMetaType::Int, 0x02005001, 		 // int IsGrabing
    81, QMetaType::Int, 0x02005001, 		 // int IsOpened
    82, QMetaType::Int, 0x02005001, 		 // int LastErrID
    312, QMetaType::Int, 0x02005001, 		 // int LostStartID
    29, 0x80000000 | 30, 0x00005001, 		 // IUnknown* ObjectHandle
    313, 0x80000000 | 314, 0x00005001, 		 // IDTImage* ROI_DTImage
    292, QMetaType::Int, 0x02015003, 		 // int ROI_X
    294, QMetaType::Int, 0x02015003, 		 // int ROI_Y
    296, QMetaType::Int, 0x02015003, 		 // int ROI_dx
    298, QMetaType::Int, 0x02015003, 		 // int ROI_dy
    300, QMetaType::Int, 0x02015003, 		 // int StreamPixelPerBytes
    302, QMetaType::Int, 0x02015003, 		 // int SubFrameHeight
    304, QMetaType::Int, 0x02015003, 		 // int TimeOut

    0 // eod
};

const QMetaObject CDTImage::staticMetaObject = {
{ &QWidget::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_DTControl__CDTImage, 0, 0, 0 }
};

void *CDTImage::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "DTControl::CDTImage"))
        return static_cast<void*>(const_cast<CDTImage*>(this));
    return QAxWidget::qt_metacast(_clname);
}
static const uint qt_meta_data_DTControl__IDTImage[] = {

 // content:
    7, // revision
    315,  // classname
    0, 0, // classinfo
    29, 14, // methods
    26, 248, // properties
    0, 0, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

// signal: name, argc, parameters, tag, flags
    12, 4, 159, 6, 5,
    17, 1, 168, 6, 5,
    19, 3, 171, 6, 5,

// slot: name, argc, parameters, tag, flags
    49, 0, 178, 6, 9,
    272, 1, 179, 6, 9,
    50, 0, 182, 6, 9,
    51, 2, 183, 6, 9,
    274, 1, 188, 6, 9,
    276, 1, 191, 6, 9,
    64, 1, 194, 6, 9,
    277, 1, 197, 6, 9,
    138, 1, 200, 6, 9,
    279, 1, 203, 6, 9,
    281, 1, 206, 6, 9,
    283, 1, 209, 6, 9,
    285, 1, 212, 6, 9,
    287, 1, 215, 6, 9,
    289, 1, 218, 6, 9,
    291, 1, 221, 6, 9,
    293, 1, 224, 6, 9,
    295, 1, 227, 6, 9,
    297, 1, 230, 6, 9,
    299, 1, 233, 6, 9,
    301, 1, 236, 6, 9,
    303, 1, 239, 6, 9,
    305, 1, 242, 6, 9,
    306, 0, 245, 6, 9,
    36, 0, 246, 6, 9,
    307, 0, 247, 6, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 13, 14, 15, 16,
    QMetaType::Void, QMetaType::QString, 18,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 18, 20, 21,

// slot: parameters
    QMetaType::Void,
    QMetaType::Int, QMetaType::Int, 273,
    QMetaType::Int,
    QMetaType::Void, QMetaType::Int, 0x80000000 | 53, 52, 54,
    QMetaType::Void, QMetaType::QString, 275,
    QMetaType::Void, QMetaType::Int, 239,
    QMetaType::Void, QMetaType::Int, 65,
    QMetaType::Void, QMetaType::Int, 278,
    QMetaType::Void, 0x80000000 | 30, 139,
    QMetaType::Void, QMetaType::Int, 280,
    QMetaType::Void, QMetaType::Int, 282,
    QMetaType::Void, QMetaType::QString, 284,
    QMetaType::Void, QMetaType::Int, 286,
    QMetaType::Void, QMetaType::Int, 288,
    QMetaType::Void, QMetaType::Int, 290,
    QMetaType::Void, QMetaType::Int, 292,
    QMetaType::Void, QMetaType::Int, 294,
    QMetaType::Void, QMetaType::Int, 296,
    QMetaType::Void, QMetaType::Int, 298,
    QMetaType::Void, QMetaType::Int, 300,
    QMetaType::Void, QMetaType::Int, 302,
    QMetaType::Void, QMetaType::Int, 304,
    QMetaType::Int, QMetaType::Int, 273,
    QMetaType::Int,
    QMetaType::Void,
    QMetaType::Void,

 // properties: name, type, flags
    308, QMetaType::Int, 0x02005001, 		 // int BandWidth
    239, QMetaType::Int, 0x02015003, 		 // int BytesPerPixel
    65, QMetaType::Int, 0x02015003, 		 // int ChannelType
    278, QMetaType::Int, 0x02015003, 		 // int DebugMode
    139, 0x80000000 | 30, 0x00015003, 		 // IUnknown* DetectorObject
    280, QMetaType::Int, 0x02015003, 		 // int DualEnergyMode
    282, QMetaType::Int, 0x02015003, 		 // int ExFrameTrigger
    284, QMetaType::QString, 0x0a015003, 		 // QString FileName
    309, 0x80000000 | 310, 0x00005001, 		 // IImageObject* ImageObject
    286, QMetaType::Int, 0x02015003, 		 // int ImagePort
    288, QMetaType::Int, 0x02015003, 		 // int ImgHeight
    290, QMetaType::Int, 0x02015003, 		 // int ImgWidth
    311, QMetaType::Int, 0x02005001, 		 // int IsGrabing
    81, QMetaType::Int, 0x02005001, 		 // int IsOpened
    82, QMetaType::Int, 0x02005001, 		 // int LastErrID
    312, QMetaType::Int, 0x02005001, 		 // int LostStartID
    29, 0x80000000 | 30, 0x00005001, 		 // IUnknown* ObjectHandle
    313, 0x80000000 | 314, 0x00005001, 		 // IDTImage* ROI_DTImage
    292, QMetaType::Int, 0x02015003, 		 // int ROI_X
    294, QMetaType::Int, 0x02015003, 		 // int ROI_Y
    296, QMetaType::Int, 0x02015003, 		 // int ROI_dx
    298, QMetaType::Int, 0x02015003, 		 // int ROI_dy
    300, QMetaType::Int, 0x02015003, 		 // int StreamPixelPerBytes
    302, QMetaType::Int, 0x02015003, 		 // int SubFrameHeight
    304, QMetaType::Int, 0x02015003, 		 // int TimeOut
    32, QMetaType::QString, 0x0a055003, 		 // QString control

    0 // eod
};

const QMetaObject IDTImage::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_DTControl__IDTImage, 0, 0, 0 }
};

void *IDTImage::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "DTControl::IDTImage"))
        return static_cast<void*>(const_cast<IDTImage*>(this));
    return QAxObject::qt_metacast(_clname);
}
static const uint qt_meta_data_DTControl__CDTDisplay[] = {

 // content:
    7, // revision
    316,  // classname
    2, 14, // classinfo
    23, 18, // methods
    16, 210, // properties
    0, 0, // enums/sets
    0, 0, // constructors
    0, // flags
    4, // signal count

 // classinfo: key, value
    1, 317, 
    3, 318, 

// signal: name, argc, parameters, tag, flags
    319, 3, 133, 6, 5,
    12, 4, 140, 6, 5,
    17, 1, 149, 6, 5,
    19, 3, 152, 6, 5,

// slot: name, argc, parameters, tag, flags
    49, 0, 159, 6, 9,
    321, 1, 160, 6, 9,
    50, 0, 163, 6, 9,
    22, 0, 164, 6, 9,
    274, 1, 165, 6, 9,
    322, 1, 168, 6, 9,
    324, 1, 171, 6, 9,
    326, 1, 174, 6, 9,
    328, 1, 177, 6, 9,
    287, 1, 180, 6, 9,
    289, 1, 183, 6, 9,
    329, 1, 186, 6, 9,
    331, 1, 189, 6, 9,
    333, 1, 192, 6, 9,
    335, 1, 195, 6, 9,
    337, 1, 198, 6, 9,
    339, 1, 201, 6, 9,
    341, 1, 204, 6, 9,
    343, 1, 207, 6, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::Int, QMetaType::Int, 241, 242, 320,
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 13, 14, 15, 16,
    QMetaType::Void, QMetaType::QString, 18,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 18, 20, 21,

// slot: parameters
    QMetaType::Void,
    QMetaType::Void, QMetaType::QString, 275,
    QMetaType::Int,
    QMetaType::Void,
    QMetaType::Void, QMetaType::QString, 275,
    QMetaType::Void, 0x80000000 | 30, 323,
    QMetaType::Void, 0x80000000 | 30, 325,
    QMetaType::Void, QMetaType::Int, 327,
    QMetaType::Void, QMetaType::Double, 9,
    QMetaType::Void, QMetaType::UInt, 288,
    QMetaType::Void, QMetaType::UInt, 290,
    QMetaType::Void, QMetaType::Int, 330,
    QMetaType::Void, QMetaType::Int, 332,
    QMetaType::Void, QMetaType::Int, 334,
    QMetaType::Void, QMetaType::Int, 336,
    QMetaType::Void, QMetaType::Int, 338,
    QMetaType::Void, QMetaType::Int, 340,
    QMetaType::Void, QMetaType::Int, 342,
    QMetaType::Void, QMetaType::Int, 344,

 // properties: name, type, flags
    323, 0x80000000 | 30, 0x00015003, 		 // IUnknown* DataSource
    325, 0x80000000 | 30, 0x00015003, 		 // IUnknown* DisplayControl
    327, QMetaType::Int, 0x02015003, 		 // int DisplayScale
    9, QMetaType::Double, 0x06015003, 		 // double Gamma
    309, 0x80000000 | 30, 0x00005001, 		 // IUnknown* ImageObject
    288, QMetaType::UInt, 0x03015003, 		 // uint ImgHeight
    290, QMetaType::UInt, 0x03015003, 		 // uint ImgWidth
    330, QMetaType::Int, 0x02015003, 		 // int InfoDisplay
    332, QMetaType::Int, 0x02015003, 		 // int MapDirection
    334, QMetaType::Int, 0x02015003, 		 // int MapEnd
    336, QMetaType::Int, 0x02015003, 		 // int MapStart
    29, 0x80000000 | 30, 0x00005001, 		 // IUnknown* ObjectHandle
    338, QMetaType::Int, 0x02015003, 		 // int OrgPoint_X
    340, QMetaType::Int, 0x02015003, 		 // int OrgPoint_Y
    342, QMetaType::Int, 0x02015003, 		 // int RefreshMode
    344, QMetaType::Int, 0x02015003, 		 // int RefreshRate

    0 // eod
};

const QMetaObject CDTDisplay::staticMetaObject = {
{ &QWidget::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_DTControl__CDTDisplay, 0, 0, 0 }
};

void *CDTDisplay::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "DTControl::CDTDisplay"))
        return static_cast<void*>(const_cast<CDTDisplay*>(this));
    return QAxWidget::qt_metacast(_clname);
}
static const uint qt_meta_data_DTControl__IDTDisplay[] = {

 // content:
    7, // revision
    345,  // classname
    0, 0, // classinfo
    22, 14, // methods
    17, 194, // properties
    0, 0, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

// signal: name, argc, parameters, tag, flags
    12, 4, 124, 6, 5,
    17, 1, 133, 6, 5,
    19, 3, 136, 6, 5,

// slot: name, argc, parameters, tag, flags
    49, 0, 143, 6, 9,
    321, 1, 144, 6, 9,
    50, 0, 147, 6, 9,
    22, 0, 148, 6, 9,
    274, 1, 149, 6, 9,
    322, 1, 152, 6, 9,
    324, 1, 155, 6, 9,
    326, 1, 158, 6, 9,
    328, 1, 161, 6, 9,
    287, 1, 164, 6, 9,
    289, 1, 167, 6, 9,
    329, 1, 170, 6, 9,
    331, 1, 173, 6, 9,
    333, 1, 176, 6, 9,
    335, 1, 179, 6, 9,
    337, 1, 182, 6, 9,
    339, 1, 185, 6, 9,
    341, 1, 188, 6, 9,
    343, 1, 191, 6, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 13, 14, 15, 16,
    QMetaType::Void, QMetaType::QString, 18,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 18, 20, 21,

// slot: parameters
    QMetaType::Void,
    QMetaType::Void, QMetaType::QString, 275,
    QMetaType::Int,
    QMetaType::Void,
    QMetaType::Void, QMetaType::QString, 275,
    QMetaType::Void, 0x80000000 | 30, 323,
    QMetaType::Void, 0x80000000 | 30, 325,
    QMetaType::Void, QMetaType::Int, 327,
    QMetaType::Void, QMetaType::Double, 9,
    QMetaType::Void, QMetaType::UInt, 288,
    QMetaType::Void, QMetaType::UInt, 290,
    QMetaType::Void, QMetaType::Int, 330,
    QMetaType::Void, QMetaType::Int, 332,
    QMetaType::Void, QMetaType::Int, 334,
    QMetaType::Void, QMetaType::Int, 336,
    QMetaType::Void, QMetaType::Int, 338,
    QMetaType::Void, QMetaType::Int, 340,
    QMetaType::Void, QMetaType::Int, 342,
    QMetaType::Void, QMetaType::Int, 344,

 // properties: name, type, flags
    323, 0x80000000 | 30, 0x00015003, 		 // IUnknown* DataSource
    325, 0x80000000 | 30, 0x00015003, 		 // IUnknown* DisplayControl
    327, QMetaType::Int, 0x02015003, 		 // int DisplayScale
    9, QMetaType::Double, 0x06015003, 		 // double Gamma
    309, 0x80000000 | 30, 0x00005001, 		 // IUnknown* ImageObject
    288, QMetaType::UInt, 0x03015003, 		 // uint ImgHeight
    290, QMetaType::UInt, 0x03015003, 		 // uint ImgWidth
    330, QMetaType::Int, 0x02015003, 		 // int InfoDisplay
    332, QMetaType::Int, 0x02015003, 		 // int MapDirection
    334, QMetaType::Int, 0x02015003, 		 // int MapEnd
    336, QMetaType::Int, 0x02015003, 		 // int MapStart
    29, 0x80000000 | 30, 0x00005001, 		 // IUnknown* ObjectHandle
    338, QMetaType::Int, 0x02015003, 		 // int OrgPoint_X
    340, QMetaType::Int, 0x02015003, 		 // int OrgPoint_Y
    342, QMetaType::Int, 0x02015003, 		 // int RefreshMode
    344, QMetaType::Int, 0x02015003, 		 // int RefreshRate
    32, QMetaType::QString, 0x0a055003, 		 // QString control

    0 // eod
};

const QMetaObject IDTDisplay::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_DTControl__IDTDisplay, 0, 0, 0 }
};

void *IDTDisplay::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "DTControl::IDTDisplay"))
        return static_cast<void*>(const_cast<IDTDisplay*>(this));
    return QAxObject::qt_metacast(_clname);
}
static const uint qt_meta_data_DTControl__CDTLog[] = {

 // content:
    7, // revision
    346,  // classname
    1, 14, // classinfo
    5, 16, // methods
    1, 66, // properties
    0, 0, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

 // classinfo: key, value
    3, 347, 

// signal: name, argc, parameters, tag, flags
    12, 4, 41, 6, 5,
    17, 1, 50, 6, 5,
    19, 3, 53, 6, 5,

// slot: name, argc, parameters, tag, flags
    348, 1, 60, 6, 9,
    350, 1, 63, 6, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 13, 14, 15, 16,
    QMetaType::Void, QMetaType::QString, 18,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 18, 20, 21,

// slot: parameters
    QMetaType::Void, QMetaType::QString, 349,
    QMetaType::Void, QMetaType::Int, 351,

 // properties: name, type, flags
    351, QMetaType::Int, 0x02015003, 		 // int LogMode

    0 // eod
};

const QMetaObject CDTLog::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_DTControl__CDTLog, 0, 0, 0 }
};

void *CDTLog::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "DTControl::CDTLog"))
        return static_cast<void*>(const_cast<CDTLog*>(this));
    return QAxObject::qt_metacast(_clname);
}
static const uint qt_meta_data_DTControl__IDTLog[] = {

 // content:
    7, // revision
    352,  // classname
    0, 0, // classinfo
    5, 14, // methods
    2, 64, // properties
    0, 0, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

// signal: name, argc, parameters, tag, flags
    12, 4, 39, 6, 5,
    17, 1, 48, 6, 5,
    19, 3, 51, 6, 5,

// slot: name, argc, parameters, tag, flags
    348, 1, 58, 6, 9,
    350, 1, 61, 6, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 13, 14, 15, 16,
    QMetaType::Void, QMetaType::QString, 18,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 18, 20, 21,

// slot: parameters
    QMetaType::Void, QMetaType::QString, 349,
    QMetaType::Void, QMetaType::Int, 351,

 // properties: name, type, flags
    351, QMetaType::Int, 0x02015003, 		 // int LogMode
    32, QMetaType::QString, 0x0a055003, 		 // QString control

    0 // eod
};

const QMetaObject IDTLog::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_DTControl__IDTLog, 0, 0, 0 }
};

void *IDTLog::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "DTControl::IDTLog"))
        return static_cast<void*>(const_cast<IDTLog*>(this));
    return QAxObject::qt_metacast(_clname);
}

