/****************************************************************************
**
** Metadata for DTControl generated by dumpcpp from type library
** ApponsDetector.dll
**
****************************************************************************/

#define QAX_DUMPCPP_DTCONTROL_NOINLINES
#include "dtcontrol.h"

using namespace DTControl;

struct qt_meta_stringdata_all_t {
    QByteArrayData data[249];
    char stringdata0[3054];
};
#define QT_MOC_LITERAL(idx, ofs, len, table) \
    Q_STATIC_BYTE_ARRAY_DATA_HEADER_INITIALIZER_WITH_OFFSET(len, \
    offsetof(qt_meta_stringdata_all_t, stringdata##table) + ofs \
        - idx * sizeof(QByteArrayData) \
    )
static const qt_meta_stringdata_all_t qt_meta_stringdata_all = {
    {
QT_MOC_LITERAL(0, 0, 28, 0),
QT_MOC_LITERAL(1, 29, 17, 0),
QT_MOC_LITERAL(2, 47, 24, 0),
QT_MOC_LITERAL(3, 72, 11, 0),
QT_MOC_LITERAL(4, 84, 17, 0),
QT_MOC_LITERAL(5, 102, 15, 0),
QT_MOC_LITERAL(6, 118, 0, 0),
QT_MOC_LITERAL(7, 119, 8, 0),
QT_MOC_LITERAL(8, 128, 20, 0),
QT_MOC_LITERAL(9, 149, 13, 0),
QT_MOC_LITERAL(10, 163, 9, 0),
QT_MOC_LITERAL(11, 173, 4, 0),
QT_MOC_LITERAL(12, 178, 6, 0),
QT_MOC_LITERAL(13, 185, 4, 0),
QT_MOC_LITERAL(14, 190, 4, 0),
QT_MOC_LITERAL(15, 195, 15, 0),
QT_MOC_LITERAL(16, 211, 4, 0),
QT_MOC_LITERAL(17, 216, 6, 0),
QT_MOC_LITERAL(18, 223, 4, 0),
QT_MOC_LITERAL(19, 228, 4, 0),
QT_MOC_LITERAL(20, 233, 11, 0),
QT_MOC_LITERAL(21, 245, 16, 0),
QT_MOC_LITERAL(22, 262, 6, 0),
QT_MOC_LITERAL(23, 269, 9, 0),
QT_MOC_LITERAL(24, 279, 28, 0),
QT_MOC_LITERAL(25, 308, 7, 0),
QT_MOC_LITERAL(26, 316, 22, 0),
QT_MOC_LITERAL(27, 339, 18, 0),
QT_MOC_LITERAL(28, 358, 11, 0),
QT_MOC_LITERAL(29, 370, 7, 0),
QT_MOC_LITERAL(30, 378, 7, 0),
QT_MOC_LITERAL(31, 386, 9, 0),
QT_MOC_LITERAL(32, 396, 5, 0),
QT_MOC_LITERAL(33, 402, 4, 0),
QT_MOC_LITERAL(34, 407, 11, 0),
QT_MOC_LITERAL(35, 419, 5, 0),
QT_MOC_LITERAL(36, 425, 8, 0),
QT_MOC_LITERAL(37, 434, 6, 0),
QT_MOC_LITERAL(38, 441, 11, 0),
QT_MOC_LITERAL(39, 453, 7, 0),
QT_MOC_LITERAL(40, 461, 9, 0),
QT_MOC_LITERAL(41, 471, 12, 0),
QT_MOC_LITERAL(42, 484, 4, 0),
QT_MOC_LITERAL(43, 489, 3, 0),
QT_MOC_LITERAL(44, 493, 3, 0),
QT_MOC_LITERAL(45, 497, 11, 0),
QT_MOC_LITERAL(46, 509, 8, 0),
QT_MOC_LITERAL(47, 518, 14, 0),
QT_MOC_LITERAL(48, 533, 11, 0),
QT_MOC_LITERAL(49, 545, 10, 0),
QT_MOC_LITERAL(50, 556, 7, 0),
QT_MOC_LITERAL(51, 564, 13, 0),
QT_MOC_LITERAL(52, 578, 10, 0),
QT_MOC_LITERAL(53, 589, 12, 0),
QT_MOC_LITERAL(54, 602, 9, 0),
QT_MOC_LITERAL(55, 612, 13, 0),
QT_MOC_LITERAL(56, 626, 10, 0),
QT_MOC_LITERAL(57, 637, 8, 0),
QT_MOC_LITERAL(58, 646, 9, 0),
QT_MOC_LITERAL(59, 656, 12, 0),
QT_MOC_LITERAL(60, 669, 22, 0),
QT_MOC_LITERAL(61, 692, 25, 0),
QT_MOC_LITERAL(62, 718, 21, 0),
QT_MOC_LITERAL(63, 740, 14, 0),
QT_MOC_LITERAL(64, 755, 4, 0),
QT_MOC_LITERAL(65, 760, 5, 0),
QT_MOC_LITERAL(66, 766, 10, 0),
QT_MOC_LITERAL(67, 777, 4, 0),
QT_MOC_LITERAL(68, 782, 8, 0),
QT_MOC_LITERAL(69, 791, 10, 0),
QT_MOC_LITERAL(70, 802, 19, 0),
QT_MOC_LITERAL(71, 822, 15, 0),
QT_MOC_LITERAL(72, 838, 10, 0),
QT_MOC_LITERAL(73, 849, 10, 0),
QT_MOC_LITERAL(74, 860, 8, 0),
QT_MOC_LITERAL(75, 869, 11, 0),
QT_MOC_LITERAL(76, 881, 6, 0),
QT_MOC_LITERAL(77, 888, 22, 0),
QT_MOC_LITERAL(78, 911, 24, 0),
QT_MOC_LITERAL(79, 936, 9, 0),
QT_MOC_LITERAL(80, 946, 11, 0),
QT_MOC_LITERAL(81, 958, 15, 0),
QT_MOC_LITERAL(82, 974, 17, 0),
QT_MOC_LITERAL(83, 992, 8, 0),
QT_MOC_LITERAL(84, 1001, 10, 0),
QT_MOC_LITERAL(85, 1012, 18, 0),
QT_MOC_LITERAL(86, 1031, 16, 0),
QT_MOC_LITERAL(87, 1048, 13, 0),
QT_MOC_LITERAL(88, 1062, 11, 0),
QT_MOC_LITERAL(89, 1074, 8, 0),
QT_MOC_LITERAL(90, 1083, 21, 0),
QT_MOC_LITERAL(91, 1105, 18, 0),
QT_MOC_LITERAL(92, 1124, 17, 0),
QT_MOC_LITERAL(93, 1142, 14, 0),
QT_MOC_LITERAL(94, 1157, 19, 0),
QT_MOC_LITERAL(95, 1177, 16, 0),
QT_MOC_LITERAL(96, 1194, 14, 0),
QT_MOC_LITERAL(97, 1209, 11, 0),
QT_MOC_LITERAL(98, 1221, 17, 0),
QT_MOC_LITERAL(99, 1239, 14, 0),
QT_MOC_LITERAL(100, 1254, 11, 0),
QT_MOC_LITERAL(101, 1266, 11, 0),
QT_MOC_LITERAL(102, 1278, 8, 0),
QT_MOC_LITERAL(103, 1287, 15, 0),
QT_MOC_LITERAL(104, 1303, 12, 0),
QT_MOC_LITERAL(105, 1316, 7, 0),
QT_MOC_LITERAL(106, 1324, 3, 0),
QT_MOC_LITERAL(107, 1328, 18, 0),
QT_MOC_LITERAL(108, 1347, 15, 0),
QT_MOC_LITERAL(109, 1363, 18, 0),
QT_MOC_LITERAL(110, 1382, 15, 0),
QT_MOC_LITERAL(111, 1398, 14, 0),
QT_MOC_LITERAL(112, 1413, 11, 0),
QT_MOC_LITERAL(113, 1425, 9, 0),
QT_MOC_LITERAL(114, 1435, 13, 0),
QT_MOC_LITERAL(115, 1449, 10, 0),
QT_MOC_LITERAL(116, 1460, 14, 0),
QT_MOC_LITERAL(117, 1475, 11, 0),
QT_MOC_LITERAL(118, 1487, 19, 0),
QT_MOC_LITERAL(119, 1507, 16, 0),
QT_MOC_LITERAL(120, 1524, 13, 0),
QT_MOC_LITERAL(121, 1538, 11, 0),
QT_MOC_LITERAL(122, 1550, 8, 0),
QT_MOC_LITERAL(123, 1559, 16, 0),
QT_MOC_LITERAL(124, 1576, 4, 0),
QT_MOC_LITERAL(125, 1581, 4, 0),
QT_MOC_LITERAL(126, 1586, 10, 0),
QT_MOC_LITERAL(127, 1597, 12, 0),
QT_MOC_LITERAL(128, 1610, 11, 0),
QT_MOC_LITERAL(129, 1622, 10, 0),
QT_MOC_LITERAL(130, 1633, 10, 0),
QT_MOC_LITERAL(131, 1644, 10, 0),
QT_MOC_LITERAL(132, 1655, 14, 0),
QT_MOC_LITERAL(133, 1670, 11, 0),
QT_MOC_LITERAL(134, 1682, 9, 0),
QT_MOC_LITERAL(135, 1692, 12, 0),
QT_MOC_LITERAL(136, 1705, 25, 0),
QT_MOC_LITERAL(137, 1731, 23, 0),
QT_MOC_LITERAL(138, 1755, 12, 0),
QT_MOC_LITERAL(139, 1768, 10, 0),
QT_MOC_LITERAL(140, 1779, 4, 0),
QT_MOC_LITERAL(141, 1784, 6, 0),
QT_MOC_LITERAL(142, 1791, 4, 0),
QT_MOC_LITERAL(143, 1796, 6, 0),
QT_MOC_LITERAL(144, 1803, 4, 0),
QT_MOC_LITERAL(145, 1808, 8, 0),
QT_MOC_LITERAL(146, 1817, 7, 0),
QT_MOC_LITERAL(147, 1825, 6, 0),
QT_MOC_LITERAL(148, 1832, 14, 0),
QT_MOC_LITERAL(149, 1847, 14, 0),
QT_MOC_LITERAL(150, 1862, 16, 0),
QT_MOC_LITERAL(151, 1879, 9, 0),
QT_MOC_LITERAL(152, 1889, 5, 0),
QT_MOC_LITERAL(153, 1895, 6, 0),
QT_MOC_LITERAL(154, 1902, 13, 0),
QT_MOC_LITERAL(155, 1916, 5, 0),
QT_MOC_LITERAL(156, 1922, 1, 0),
QT_MOC_LITERAL(157, 1924, 1, 0),
QT_MOC_LITERAL(158, 1926, 10, 0),
QT_MOC_LITERAL(159, 1937, 6, 0),
QT_MOC_LITERAL(160, 1944, 6, 0),
QT_MOC_LITERAL(161, 1951, 8, 0),
QT_MOC_LITERAL(162, 1960, 19, 0),
QT_MOC_LITERAL(163, 1980, 16, 0),
QT_MOC_LITERAL(164, 1997, 8, 0),
QT_MOC_LITERAL(165, 2006, 23, 0),
QT_MOC_LITERAL(166, 2030, 21, 0),
QT_MOC_LITERAL(167, 2052, 17, 0),
QT_MOC_LITERAL(168, 2070, 10, 0),
QT_MOC_LITERAL(169, 2081, 9, 0),
QT_MOC_LITERAL(170, 2091, 5, 0),
QT_MOC_LITERAL(171, 2097, 4, 0),
QT_MOC_LITERAL(172, 2102, 8, 0),
QT_MOC_LITERAL(173, 2111, 7, 0),
QT_MOC_LITERAL(174, 2119, 7, 0),
QT_MOC_LITERAL(175, 2127, 4, 0),
QT_MOC_LITERAL(176, 2132, 13, 0),
QT_MOC_LITERAL(177, 2146, 10, 0),
QT_MOC_LITERAL(178, 2157, 17, 0),
QT_MOC_LITERAL(179, 2175, 14, 0),
QT_MOC_LITERAL(180, 2190, 15, 0),
QT_MOC_LITERAL(181, 2206, 12, 0),
QT_MOC_LITERAL(182, 2219, 8, 0),
QT_MOC_LITERAL(183, 2228, 5, 0),
QT_MOC_LITERAL(184, 2234, 12, 0),
QT_MOC_LITERAL(185, 2247, 9, 0),
QT_MOC_LITERAL(186, 2257, 11, 0),
QT_MOC_LITERAL(187, 2269, 8, 0),
QT_MOC_LITERAL(188, 2278, 9, 0),
QT_MOC_LITERAL(189, 2288, 6, 0),
QT_MOC_LITERAL(190, 2295, 11, 0),
QT_MOC_LITERAL(191, 2307, 8, 0),
QT_MOC_LITERAL(192, 2316, 13, 0),
QT_MOC_LITERAL(193, 2330, 10, 0),
QT_MOC_LITERAL(194, 2341, 13, 0),
QT_MOC_LITERAL(195, 2355, 10, 0),
QT_MOC_LITERAL(196, 2366, 14, 0),
QT_MOC_LITERAL(197, 2381, 11, 0),
QT_MOC_LITERAL(198, 2393, 14, 0),
QT_MOC_LITERAL(199, 2408, 11, 0),
QT_MOC_LITERAL(200, 2420, 11, 0),
QT_MOC_LITERAL(201, 2432, 21, 0),
QT_MOC_LITERAL(202, 2454, 19, 0),
QT_MOC_LITERAL(203, 2474, 15, 0),
QT_MOC_LITERAL(204, 2490, 8, 0),
QT_MOC_LITERAL(205, 2499, 8, 0),
QT_MOC_LITERAL(206, 2508, 11, 0),
QT_MOC_LITERAL(207, 2520, 10, 0),
QT_MOC_LITERAL(208, 2531, 8, 0),
QT_MOC_LITERAL(209, 2540, 13, 0),
QT_MOC_LITERAL(210, 2554, 14, 0),
QT_MOC_LITERAL(211, 2569, 9, 0),
QT_MOC_LITERAL(212, 2579, 10, 0),
QT_MOC_LITERAL(213, 2590, 12, 0),
QT_MOC_LITERAL(214, 2603, 11, 0),
QT_MOC_LITERAL(215, 2615, 15, 0),
QT_MOC_LITERAL(216, 2631, 6, 0),
QT_MOC_LITERAL(217, 2638, 4, 0),
QT_MOC_LITERAL(218, 2643, 8, 0),
QT_MOC_LITERAL(219, 2652, 17, 0),
QT_MOC_LITERAL(220, 2670, 12, 0),
QT_MOC_LITERAL(221, 2683, 5, 0),
QT_MOC_LITERAL(222, 2689, 4, 0),
QT_MOC_LITERAL(223, 2694, 16, 0),
QT_MOC_LITERAL(224, 2711, 15, 0),
QT_MOC_LITERAL(225, 2727, 12, 0),
QT_MOC_LITERAL(226, 2740, 17, 0),
QT_MOC_LITERAL(227, 2758, 14, 0),
QT_MOC_LITERAL(228, 2773, 13, 0),
QT_MOC_LITERAL(229, 2787, 10, 0),
QT_MOC_LITERAL(230, 2798, 12, 0),
QT_MOC_LITERAL(231, 2811, 9, 0),
QT_MOC_LITERAL(232, 2821, 15, 0),
QT_MOC_LITERAL(233, 2837, 12, 0),
QT_MOC_LITERAL(234, 2850, 19, 0),
QT_MOC_LITERAL(235, 2870, 16, 0),
QT_MOC_LITERAL(236, 2887, 9, 0),
QT_MOC_LITERAL(237, 2897, 6, 0),
QT_MOC_LITERAL(238, 2904, 17, 0),
QT_MOC_LITERAL(239, 2922, 14, 0),
QT_MOC_LITERAL(240, 2937, 10, 0),
QT_MOC_LITERAL(241, 2948, 7, 0),
QT_MOC_LITERAL(242, 2956, 4, 0),
QT_MOC_LITERAL(243, 2961, 4, 0),
QT_MOC_LITERAL(244, 2966, 24, 0),
QT_MOC_LITERAL(245, 2991, 21, 0),
QT_MOC_LITERAL(246, 3013, 9, 0),
QT_MOC_LITERAL(247, 3023, 9, 0),
QT_MOC_LITERAL(248, 3033, 19, 0)
    },
    "DTControl::CDTDisplayControl\0Event Interface 1\0_IDTDisplayControlEvents\0"
    "Interface 0\0IDTDisplayControl\0AutoSizeChanged\0\0AutoSize\0BorderVisibleChanged\0"
    "BorderVisible\0exception\0code\0source\0disc\0help\0propertyChanged\0name\0signal\0"
    "argc\0argv\0SetAutoSize\0SetBorderVisible\0Object\0IUnknown*\0DTControl::IDTDisplayControl\0"
    "control\0DTControl::CDTDetector\0_IDTDetectorEvents\0IDTDetector\0DTError\0ErrorID\0"
    "ErrorInfo\0Close\0Open\0PrintErrMsg\0ErrID\0QString&\0ErrMsg\0SendCommand\0bstrCmd\0"
    "bstrRTMsg\0SendCommandA\0int&\0Cmd\0pRT\0SetBaudRate\0BaudRate\0SetChannelType\0"
    "ChannelType\0SetCmdPort\0CmdPort\0SetCmdTimeOut\0CmdTimeOut\0SetIPAddress\0IPAddress\0"
    "SetSerialPort\0SerialPort\0IsOpened\0LastErrID\0ObjectHandle\0DTControl::IDTDetector\0"
    "DTControl::CDTCommanderF3\0_IDTCommanderF3Events\0IDTCommanderF3\0Gain\0Index\0"
    "Initialize\0Mode\0LoadGain\0LoadOffset\0OffBoardCalibration\0CalibrationType\0"
    "pImgObject\0StartPixel\0EndPixel\0TargetValue\0Offset\0OnBoardGainCalibration\0"
    "OnBoardOffsetCalibration\0ResetGain\0ResetOffset\0RetrieveSysinfo\0SaveCurrentStatus\0"
    "SaveGain\0SaveOffset\0SendExFrameTrigger\0SetAverageFilter\0AverageFilter\0"
    "SetBaseline\0Baseline\0SetCorrectionBaseline\0CorrectionBaseline\0SetCorrectionGain\0"
    "CorrectionGain\0SetCorrectionOffset\0CorrectionOffset\0SetDataPattern\0DataPattern\0"
    "SetDetectorObject\0DetectorObject\0SetEndPixel\0SetFrameOut\0FrameOut\0SetFrameTrigger\0"
    "FrameTrigger\0SetGain\0rhs\0SetImageOutputType\0ImageOutputType\0SetIntegrationTime\0"
    "IntegrationTime\0SetLineTrigger\0LineTrigger\0SetOffset\0SetOutputBits\0OutputBits\0"
    "SetOverallGain\0OverallGain\0SetSensitivityLevel\0SensitivityLevel\0SetStartPixel\0"
    "SetSumLines\0SumLines\0WriteDataPattern\0Base\0Step\0FPGA_Build\0FPGA_Version\0"
    "MCU_Version\0MaxIntTime\0MinIntTime\0ModuleType\0ModuleTypeName\0PixelNumber\0"
    "PixelSize\0SerialNumber\0DTControl::IDTCommanderF3\0DTControl::CImageObject\0"
    "IImageObject\0ColAverage\0pAvg\0ColMax\0pMax\0ColMin\0pMin\0ColNoise\0double&\0pNoise\0"
    "DoColStatistic\0DoRowStatistic\0ImageLineAddress\0LineIndex\0Width\0Height\0"
    "BytesPerPixel\0Pixel\0X\0Y\0RowAverage\0RowMax\0RowMin\0RowNoise\0SetImageDataAddress\0"
    "ImageDataAddress\0SetPixel\0DTControl::IImageObject\0DTControl::CDTDisplay\0"
    "_IDTDisplayEvents\0IDTDisplay\0MouseMove\0Value\0Load\0FilePath\0Refresh\0Repaint\0"
    "Save\0SetDataSource\0DataSource\0SetDisplayControl\0DisplayControl\0SetDisplayScale\0"
    "DisplayScale\0SetGamma\0Gamma\0SetImgHeight\0ImgHeight\0SetImgWidth\0ImgWidth\0"
    "SetMapEnd\0MapEnd\0SetMapStart\0MapStart\0SetOrgPoint_X\0OrgPoint_X\0SetOrgPoint_Y\0"
    "OrgPoint_Y\0SetRefreshMode\0RefreshMode\0SetRefreshRate\0RefreshRate\0ImageObject\0"
    "DTControl::IDTDisplay\0DTControl::CDTImage\0_IDTImageEvents\0IDTImage\0Datalost\0"
    "LostlineNum\0FrameReady\0NumLines\0SubFrameReady\0NumOfBlockLeft\0StartLine\0"
    "bLastBlock\0GainArrayCal\0GainCalSnap\0GainCalibration\0target\0Grab\0FrameNum\0"
    "OffsetCalibration\0OpenMemImage\0uint&\0data\0SetBytesPerPixel\0SetDualScanMode\0"
    "DualScanMode\0SetExFrameTrigger\0ExFrameTrigger\0SetGainEnable\0GainEnable\0"
    "SetImagePort\0ImagePort\0SetOffsetEnable\0OffsetEnable\0SetPixelOrderEnable\0"
    "PixelOrderEnable\0SetRevert\0Revert\0SetSubFrameHeight\0SubFrameHeight\0SetTimeOut\0"
    "TimeOut\0Snap\0Stop\0setArrayCorrectionEnable\0arrayCorrectionEnable\0BandWidth\0"
    "IsGrabing\0DTControl::IDTImage\0"
};
#undef QT_MOC_LITERAL

static const uint qt_meta_data_DTControl__CDTDisplayControl[] = {

 // content:
    7, // revision
    0,  // classname
    2, 14, // classinfo
    7, 18, // methods
    3, 84, // properties
    0, 0, // enums/sets
    0, 0, // constructors
    0, // flags
    5, // signal count

 // classinfo: key, value
    1, 2, 
    3, 4, 

// signal: name, argc, parameters, tag, flags
    5, 1, 53, 6, 5,
    8, 1, 56, 6, 5,
    10, 4, 59, 6, 5,
    15, 1, 68, 6, 5,
    17, 3, 71, 6, 5,

// slot: name, argc, parameters, tag, flags
    20, 1, 78, 6, 9,
    21, 1, 81, 6, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Bool, 7,
    QMetaType::Void, QMetaType::Bool, 9,
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 11, 12, 13, 14,
    QMetaType::Void, QMetaType::QString, 16,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 16, 18, 19,

// slot: parameters
    QMetaType::Void, QMetaType::Bool, 7,
    QMetaType::Void, QMetaType::Bool, 9,

 // properties: name, type, flags
    7, QMetaType::Bool, 0x01005001, 		 // bool AutoSize
    9, QMetaType::Bool, 0x01005001, 		 // bool BorderVisible
    22, 0x80000000 | 23, 0x00005001, 		 // IUnknown* Object

    0 // eod
};

const QMetaObject CDTDisplayControl::staticMetaObject = {
{ &QWidget::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_DTControl__CDTDisplayControl, 0, 0, 0 }
};

void *CDTDisplayControl::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "DTControl::CDTDisplayControl"))
        return static_cast<void*>(const_cast<CDTDisplayControl*>(this));
    return QAxWidget::qt_metacast(_clname);
}
static const uint qt_meta_data_DTControl__IDTDisplayControl[] = {

 // content:
    7, // revision
    24,  // classname
    0, 0, // classinfo
    7, 14, // methods
    4, 80, // properties
    0, 0, // enums/sets
    0, 0, // constructors
    0, // flags
    5, // signal count

// signal: name, argc, parameters, tag, flags
    5, 1, 49, 6, 5,
    8, 1, 52, 6, 5,
    10, 4, 55, 6, 5,
    15, 1, 64, 6, 5,
    17, 3, 67, 6, 5,

// slot: name, argc, parameters, tag, flags
    20, 1, 74, 6, 9,
    21, 1, 77, 6, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Bool, 7,
    QMetaType::Void, QMetaType::Bool, 9,
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 11, 12, 13, 14,
    QMetaType::Void, QMetaType::QString, 16,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 16, 18, 19,

// slot: parameters
    QMetaType::Void, QMetaType::Bool, 7,
    QMetaType::Void, QMetaType::Bool, 9,

 // properties: name, type, flags
    7, QMetaType::Bool, 0x01005001, 		 // bool AutoSize
    9, QMetaType::Bool, 0x01005001, 		 // bool BorderVisible
    22, 0x80000000 | 23, 0x00005001, 		 // IUnknown* Object
    25, QMetaType::QString, 0x0a055003, 		 // QString control

    0 // eod
};

const QMetaObject IDTDisplayControl::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_DTControl__IDTDisplayControl, 0, 0, 0 }
};

void *IDTDisplayControl::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "DTControl::IDTDisplayControl"))
        return static_cast<void*>(const_cast<IDTDisplayControl*>(this));
    return QAxObject::qt_metacast(_clname);
}
static const uint qt_meta_data_DTControl__CDTDetector[] = {

 // content:
    7, // revision
    26,  // classname
    2, 14, // classinfo
    15, 18, // methods
    9, 152, // properties
    0, 0, // enums/sets
    0, 0, // constructors
    0, // flags
    4, // signal count

 // classinfo: key, value
    1, 27, 
    3, 28, 

// signal: name, argc, parameters, tag, flags
    29, 2, 93, 6, 5,
    10, 4, 98, 6, 5,
    15, 1, 107, 6, 5,
    17, 3, 110, 6, 5,

// slot: name, argc, parameters, tag, flags
    32, 0, 117, 6, 9,
    33, 0, 118, 6, 9,
    34, 2, 119, 6, 9,
    38, 2, 124, 6, 9,
    41, 2, 129, 6, 9,
    45, 1, 134, 6, 9,
    47, 1, 137, 6, 9,
    49, 1, 140, 6, 9,
    51, 1, 143, 6, 9,
    53, 1, 146, 6, 9,
    55, 1, 149, 6, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, 30, 31,
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 11, 12, 13, 14,
    QMetaType::Void, QMetaType::QString, 16,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 16, 18, 19,

// slot: parameters
    QMetaType::Void,
    QMetaType::Int,
    QMetaType::Void, QMetaType::Int, 0x80000000 | 36, 35, 37,
    QMetaType::Int, QMetaType::QString, 0x80000000 | 36, 39, 40,
    QMetaType::Int, 0x80000000 | 42, 0x80000000 | 42, 43, 44,
    QMetaType::Void, QMetaType::Int, 46,
    QMetaType::Void, QMetaType::Int, 48,
    QMetaType::Void, QMetaType::Int, 50,
    QMetaType::Void, QMetaType::Int, 52,
    QMetaType::Void, QMetaType::QString, 54,
    QMetaType::Void, QMetaType::Int, 56,

 // properties: name, type, flags
    46, QMetaType::Int, 0x02015003, 		 // int BaudRate
    48, QMetaType::Int, 0x02015003, 		 // int ChannelType
    50, QMetaType::Int, 0x02015003, 		 // int CmdPort
    52, QMetaType::Int, 0x02015003, 		 // int CmdTimeOut
    54, QMetaType::QString, 0x0a015003, 		 // QString IPAddress
    57, QMetaType::Int, 0x02005001, 		 // int IsOpened
    58, QMetaType::Int, 0x02005001, 		 // int LastErrID
    59, 0x80000000 | 23, 0x00005001, 		 // IUnknown* ObjectHandle
    56, QMetaType::Int, 0x02015003, 		 // int SerialPort

    0 // eod
};

const QMetaObject CDTDetector::staticMetaObject = {
{ &QWidget::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_DTControl__CDTDetector, 0, 0, 0 }
};

void *CDTDetector::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "DTControl::CDTDetector"))
        return static_cast<void*>(const_cast<CDTDetector*>(this));
    return QAxWidget::qt_metacast(_clname);
}
static const uint qt_meta_data_DTControl__IDTDetector[] = {

 // content:
    7, // revision
    60,  // classname
    0, 0, // classinfo
    14, 14, // methods
    10, 138, // properties
    0, 0, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

// signal: name, argc, parameters, tag, flags
    10, 4, 84, 6, 5,
    15, 1, 93, 6, 5,
    17, 3, 96, 6, 5,

// slot: name, argc, parameters, tag, flags
    32, 0, 103, 6, 9,
    33, 0, 104, 6, 9,
    34, 2, 105, 6, 9,
    38, 2, 110, 6, 9,
    41, 2, 115, 6, 9,
    45, 1, 120, 6, 9,
    47, 1, 123, 6, 9,
    49, 1, 126, 6, 9,
    51, 1, 129, 6, 9,
    53, 1, 132, 6, 9,
    55, 1, 135, 6, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 11, 12, 13, 14,
    QMetaType::Void, QMetaType::QString, 16,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 16, 18, 19,

// slot: parameters
    QMetaType::Void,
    QMetaType::Int,
    QMetaType::Void, QMetaType::Int, 0x80000000 | 36, 35, 37,
    QMetaType::Int, QMetaType::QString, 0x80000000 | 36, 39, 40,
    QMetaType::Int, 0x80000000 | 42, 0x80000000 | 42, 43, 44,
    QMetaType::Void, QMetaType::Int, 46,
    QMetaType::Void, QMetaType::Int, 48,
    QMetaType::Void, QMetaType::Int, 50,
    QMetaType::Void, QMetaType::Int, 52,
    QMetaType::Void, QMetaType::QString, 54,
    QMetaType::Void, QMetaType::Int, 56,

 // properties: name, type, flags
    46, QMetaType::Int, 0x02015003, 		 // int BaudRate
    48, QMetaType::Int, 0x02015003, 		 // int ChannelType
    50, QMetaType::Int, 0x02015003, 		 // int CmdPort
    52, QMetaType::Int, 0x02015003, 		 // int CmdTimeOut
    54, QMetaType::QString, 0x0a015003, 		 // QString IPAddress
    57, QMetaType::Int, 0x02005001, 		 // int IsOpened
    58, QMetaType::Int, 0x02005001, 		 // int LastErrID
    59, 0x80000000 | 23, 0x00005001, 		 // IUnknown* ObjectHandle
    56, QMetaType::Int, 0x02015003, 		 // int SerialPort
    25, QMetaType::QString, 0x0a055003, 		 // QString control

    0 // eod
};

const QMetaObject IDTDetector::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_DTControl__IDTDetector, 0, 0, 0 }
};

void *IDTDetector::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "DTControl::IDTDetector"))
        return static_cast<void*>(const_cast<IDTDetector*>(this));
    return QAxObject::qt_metacast(_clname);
}
static const uint qt_meta_data_DTControl__CDTCommanderF3[] = {

 // content:
    7, // revision
    61,  // classname
    2, 14, // classinfo
    39, 18, // methods
    29, 338, // properties
    0, 0, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

 // classinfo: key, value
    1, 62, 
    3, 63, 

// signal: name, argc, parameters, tag, flags
    10, 4, 213, 6, 5,
    15, 1, 222, 6, 5,
    17, 3, 225, 6, 5,

// slot: name, argc, parameters, tag, flags
    64, 1, 232, 6, 9,
    66, 1, 235, 6, 9,
    68, 1, 238, 6, 9,
    69, 0, 241, 6, 9,
    70, 5, 242, 6, 9,
    76, 1, 253, 6, 9,
    77, 1, 256, 6, 9,
    78, 0, 259, 6, 9,
    79, 0, 260, 6, 9,
    80, 0, 261, 6, 9,
    81, 0, 262, 6, 9,
    82, 0, 263, 6, 9,
    83, 1, 264, 6, 9,
    84, 0, 267, 6, 9,
    85, 0, 268, 6, 9,
    86, 1, 269, 6, 9,
    88, 1, 272, 6, 9,
    90, 1, 275, 6, 9,
    92, 1, 278, 6, 9,
    94, 1, 281, 6, 9,
    96, 1, 284, 6, 9,
    98, 1, 287, 6, 9,
    100, 1, 290, 6, 9,
    101, 1, 293, 6, 9,
    103, 1, 296, 6, 9,
    105, 2, 299, 6, 9,
    107, 1, 304, 6, 9,
    109, 1, 307, 6, 9,
    111, 1, 310, 6, 9,
    113, 2, 313, 6, 9,
    114, 1, 318, 6, 9,
    116, 1, 321, 6, 9,
    118, 1, 324, 6, 9,
    120, 1, 327, 6, 9,
    121, 1, 330, 6, 9,
    123, 2, 333, 6, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 11, 12, 13, 14,
    QMetaType::Void, QMetaType::QString, 16,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 16, 18, 19,

// slot: parameters
    QMetaType::Double, QMetaType::Int, 65,
    QMetaType::Void, QMetaType::Int, 67,
    QMetaType::Void, QMetaType::Int, 65,
    QMetaType::Void,
    QMetaType::Void, QMetaType::Int, 0x80000000 | 23, QMetaType::Int, QMetaType::Int, QMetaType::Int, 71, 72, 73, 74, 75,
    QMetaType::Int, QMetaType::Int, 65,
    QMetaType::Void, QMetaType::Int, 75,
    QMetaType::Void,
    QMetaType::Void,
    QMetaType::Void,
    QMetaType::Void,
    QMetaType::Void,
    QMetaType::Void, QMetaType::Int, 65,
    QMetaType::Void,
    QMetaType::Void,
    QMetaType::Void, QMetaType::Int, 87,
    QMetaType::Void, QMetaType::Int, 89,
    QMetaType::Void, QMetaType::Int, 91,
    QMetaType::Void, QMetaType::Int, 93,
    QMetaType::Void, QMetaType::Int, 95,
    QMetaType::Void, QMetaType::Int, 97,
    QMetaType::Void, 0x80000000 | 23, 99,
    QMetaType::Void, QMetaType::Int, 74,
    QMetaType::Void, QMetaType::Int, 102,
    QMetaType::Void, QMetaType::Int, 104,
    QMetaType::Void, QMetaType::Int, QMetaType::Double, 65, 106,
    QMetaType::Void, QMetaType::Int, 108,
    QMetaType::Void, QMetaType::Int, 110,
    QMetaType::Void, QMetaType::Int, 112,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, 65, 106,
    QMetaType::Void, QMetaType::Int, 115,
    QMetaType::Void, QMetaType::Double, 117,
    QMetaType::Void, QMetaType::Int, 119,
    QMetaType::Void, QMetaType::Int, 73,
    QMetaType::Void, QMetaType::Int, 122,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, 124, 125,

 // properties: name, type, flags
    87, QMetaType::Int, 0x02015003, 		 // int AverageFilter
    89, QMetaType::Int, 0x02015003, 		 // int Baseline
    91, QMetaType::Int, 0x02015003, 		 // int CorrectionBaseline
    93, QMetaType::Int, 0x02015003, 		 // int CorrectionGain
    95, QMetaType::Int, 0x02015003, 		 // int CorrectionOffset
    97, QMetaType::Int, 0x02015003, 		 // int DataPattern
    99, 0x80000000 | 23, 0x00015003, 		 // IUnknown* DetectorObject
    74, QMetaType::Int, 0x02015003, 		 // int EndPixel
    126, QMetaType::Int, 0x02005001, 		 // int FPGA_Build
    127, QMetaType::Int, 0x02005001, 		 // int FPGA_Version
    102, QMetaType::Int, 0x02015003, 		 // int FrameOut
    104, QMetaType::Int, 0x02015003, 		 // int FrameTrigger
    108, QMetaType::Int, 0x02015003, 		 // int ImageOutputType
    110, QMetaType::Int, 0x02015003, 		 // int IntegrationTime
    57, QMetaType::Int, 0x02005001, 		 // int IsOpened
    112, QMetaType::Int, 0x02015003, 		 // int LineTrigger
    128, QMetaType::Int, 0x02005001, 		 // int MCU_Version
    129, QMetaType::Int, 0x02005001, 		 // int MaxIntTime
    130, QMetaType::Int, 0x02005001, 		 // int MinIntTime
    131, QMetaType::Int, 0x02005001, 		 // int ModuleType
    132, QMetaType::QString, 0x0a005001, 		 // QString ModuleTypeName
    115, QMetaType::Int, 0x02015003, 		 // int OutputBits
    117, QMetaType::Double, 0x06015003, 		 // double OverallGain
    133, QMetaType::Int, 0x02005001, 		 // int PixelNumber
    134, QMetaType::Double, 0x06005001, 		 // double PixelSize
    119, QMetaType::Int, 0x02015003, 		 // int SensitivityLevel
    135, QMetaType::QString, 0x0a005001, 		 // QString SerialNumber
    73, QMetaType::Int, 0x02015003, 		 // int StartPixel
    122, QMetaType::Int, 0x02015003, 		 // int SumLines

    0 // eod
};

const QMetaObject CDTCommanderF3::staticMetaObject = {
{ &QWidget::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_DTControl__CDTCommanderF3, 0, 0, 0 }
};

void *CDTCommanderF3::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "DTControl::CDTCommanderF3"))
        return static_cast<void*>(const_cast<CDTCommanderF3*>(this));
    return QAxWidget::qt_metacast(_clname);
}
static const uint qt_meta_data_DTControl__IDTCommanderF3[] = {

 // content:
    7, // revision
    136,  // classname
    0, 0, // classinfo
    39, 14, // methods
    30, 334, // properties
    0, 0, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

// signal: name, argc, parameters, tag, flags
    10, 4, 209, 6, 5,
    15, 1, 218, 6, 5,
    17, 3, 221, 6, 5,

// slot: name, argc, parameters, tag, flags
    64, 1, 228, 6, 9,
    66, 1, 231, 6, 9,
    68, 1, 234, 6, 9,
    69, 0, 237, 6, 9,
    70, 5, 238, 6, 9,
    76, 1, 249, 6, 9,
    77, 1, 252, 6, 9,
    78, 0, 255, 6, 9,
    79, 0, 256, 6, 9,
    80, 0, 257, 6, 9,
    81, 0, 258, 6, 9,
    82, 0, 259, 6, 9,
    83, 1, 260, 6, 9,
    84, 0, 263, 6, 9,
    85, 0, 264, 6, 9,
    86, 1, 265, 6, 9,
    88, 1, 268, 6, 9,
    90, 1, 271, 6, 9,
    92, 1, 274, 6, 9,
    94, 1, 277, 6, 9,
    96, 1, 280, 6, 9,
    98, 1, 283, 6, 9,
    100, 1, 286, 6, 9,
    101, 1, 289, 6, 9,
    103, 1, 292, 6, 9,
    105, 2, 295, 6, 9,
    107, 1, 300, 6, 9,
    109, 1, 303, 6, 9,
    111, 1, 306, 6, 9,
    113, 2, 309, 6, 9,
    114, 1, 314, 6, 9,
    116, 1, 317, 6, 9,
    118, 1, 320, 6, 9,
    120, 1, 323, 6, 9,
    121, 1, 326, 6, 9,
    123, 2, 329, 6, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 11, 12, 13, 14,
    QMetaType::Void, QMetaType::QString, 16,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 16, 18, 19,

// slot: parameters
    QMetaType::Double, QMetaType::Int, 65,
    QMetaType::Void, QMetaType::Int, 67,
    QMetaType::Void, QMetaType::Int, 65,
    QMetaType::Void,
    QMetaType::Void, QMetaType::Int, 0x80000000 | 23, QMetaType::Int, QMetaType::Int, QMetaType::Int, 71, 72, 73, 74, 75,
    QMetaType::Int, QMetaType::Int, 65,
    QMetaType::Void, QMetaType::Int, 75,
    QMetaType::Void,
    QMetaType::Void,
    QMetaType::Void,
    QMetaType::Void,
    QMetaType::Void,
    QMetaType::Void, QMetaType::Int, 65,
    QMetaType::Void,
    QMetaType::Void,
    QMetaType::Void, QMetaType::Int, 87,
    QMetaType::Void, QMetaType::Int, 89,
    QMetaType::Void, QMetaType::Int, 91,
    QMetaType::Void, QMetaType::Int, 93,
    QMetaType::Void, QMetaType::Int, 95,
    QMetaType::Void, QMetaType::Int, 97,
    QMetaType::Void, 0x80000000 | 23, 99,
    QMetaType::Void, QMetaType::Int, 74,
    QMetaType::Void, QMetaType::Int, 102,
    QMetaType::Void, QMetaType::Int, 104,
    QMetaType::Void, QMetaType::Int, QMetaType::Double, 65, 106,
    QMetaType::Void, QMetaType::Int, 108,
    QMetaType::Void, QMetaType::Int, 110,
    QMetaType::Void, QMetaType::Int, 112,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, 65, 106,
    QMetaType::Void, QMetaType::Int, 115,
    QMetaType::Void, QMetaType::Double, 117,
    QMetaType::Void, QMetaType::Int, 119,
    QMetaType::Void, QMetaType::Int, 73,
    QMetaType::Void, QMetaType::Int, 122,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, 124, 125,

 // properties: name, type, flags
    87, QMetaType::Int, 0x02015003, 		 // int AverageFilter
    89, QMetaType::Int, 0x02015003, 		 // int Baseline
    91, QMetaType::Int, 0x02015003, 		 // int CorrectionBaseline
    93, QMetaType::Int, 0x02015003, 		 // int CorrectionGain
    95, QMetaType::Int, 0x02015003, 		 // int CorrectionOffset
    97, QMetaType::Int, 0x02015003, 		 // int DataPattern
    99, 0x80000000 | 23, 0x00015003, 		 // IUnknown* DetectorObject
    74, QMetaType::Int, 0x02015003, 		 // int EndPixel
    126, QMetaType::Int, 0x02005001, 		 // int FPGA_Build
    127, QMetaType::Int, 0x02005001, 		 // int FPGA_Version
    102, QMetaType::Int, 0x02015003, 		 // int FrameOut
    104, QMetaType::Int, 0x02015003, 		 // int FrameTrigger
    108, QMetaType::Int, 0x02015003, 		 // int ImageOutputType
    110, QMetaType::Int, 0x02015003, 		 // int IntegrationTime
    57, QMetaType::Int, 0x02005001, 		 // int IsOpened
    112, QMetaType::Int, 0x02015003, 		 // int LineTrigger
    128, QMetaType::Int, 0x02005001, 		 // int MCU_Version
    129, QMetaType::Int, 0x02005001, 		 // int MaxIntTime
    130, QMetaType::Int, 0x02005001, 		 // int MinIntTime
    131, QMetaType::Int, 0x02005001, 		 // int ModuleType
    132, QMetaType::QString, 0x0a005001, 		 // QString ModuleTypeName
    115, QMetaType::Int, 0x02015003, 		 // int OutputBits
    117, QMetaType::Double, 0x06015003, 		 // double OverallGain
    133, QMetaType::Int, 0x02005001, 		 // int PixelNumber
    134, QMetaType::Double, 0x06005001, 		 // double PixelSize
    119, QMetaType::Int, 0x02015003, 		 // int SensitivityLevel
    135, QMetaType::QString, 0x0a005001, 		 // QString SerialNumber
    73, QMetaType::Int, 0x02015003, 		 // int StartPixel
    122, QMetaType::Int, 0x02015003, 		 // int SumLines
    25, QMetaType::QString, 0x0a055003, 		 // QString control

    0 // eod
};

const QMetaObject IDTCommanderF3::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_DTControl__IDTCommanderF3, 0, 0, 0 }
};

void *IDTCommanderF3::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "DTControl::IDTCommanderF3"))
        return static_cast<void*>(const_cast<IDTCommanderF3*>(this));
    return QAxObject::qt_metacast(_clname);
}
static const uint qt_meta_data_DTControl__CImageObject[] = {

 // content:
    7, // revision
    137,  // classname
    1, 14, // classinfo
    18, 16, // methods
    4, 176, // properties
    0, 0, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

 // classinfo: key, value
    3, 138, 

// signal: name, argc, parameters, tag, flags
    10, 4, 106, 6, 5,
    15, 1, 115, 6, 5,
    17, 3, 118, 6, 5,

// slot: name, argc, parameters, tag, flags
    139, 1, 125, 6, 9,
    141, 1, 128, 6, 9,
    143, 1, 131, 6, 9,
    145, 1, 134, 6, 9,
    148, 0, 137, 6, 9,
    149, 0, 138, 6, 9,
    150, 1, 139, 6, 9,
    33, 3, 142, 6, 9,
    155, 2, 149, 6, 9,
    158, 1, 154, 6, 9,
    159, 1, 157, 6, 9,
    160, 1, 160, 6, 9,
    161, 1, 163, 6, 9,
    162, 1, 166, 6, 9,
    164, 3, 169, 6, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 11, 12, 13, 14,
    QMetaType::Void, QMetaType::QString, 16,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 16, 18, 19,

// slot: parameters
    QMetaType::Void, 0x80000000 | 42, 140,
    QMetaType::Void, 0x80000000 | 42, 142,
    QMetaType::Void, 0x80000000 | 42, 144,
    QMetaType::Void, 0x80000000 | 146, 147,
    QMetaType::Void,
    QMetaType::Void,
    QMetaType::Int, QMetaType::Int, 151,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, QMetaType::Int, 152, 153, 154,
    QMetaType::Int, QMetaType::Int, QMetaType::Int, 156, 157,
    QMetaType::Void, 0x80000000 | 42, 140,
    QMetaType::Void, 0x80000000 | 42, 142,
    QMetaType::Void, 0x80000000 | 42, 144,
    QMetaType::Void, 0x80000000 | 146, 147,
    QMetaType::Void, QMetaType::Int, 163,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, QMetaType::Int, 156, 157, 106,

 // properties: name, type, flags
    154, QMetaType::Int, 0x02005001, 		 // int BytesPerPixel
    153, QMetaType::Int, 0x02005001, 		 // int Height
    163, QMetaType::Int, 0x02015003, 		 // int ImageDataAddress
    152, QMetaType::Int, 0x02005001, 		 // int Width

    0 // eod
};

const QMetaObject CImageObject::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_DTControl__CImageObject, 0, 0, 0 }
};

void *CImageObject::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "DTControl::CImageObject"))
        return static_cast<void*>(const_cast<CImageObject*>(this));
    return QAxObject::qt_metacast(_clname);
}
static const uint qt_meta_data_DTControl__IImageObject[] = {

 // content:
    7, // revision
    165,  // classname
    0, 0, // classinfo
    18, 14, // methods
    5, 174, // properties
    0, 0, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

// signal: name, argc, parameters, tag, flags
    10, 4, 104, 6, 5,
    15, 1, 113, 6, 5,
    17, 3, 116, 6, 5,

// slot: name, argc, parameters, tag, flags
    139, 1, 123, 6, 9,
    141, 1, 126, 6, 9,
    143, 1, 129, 6, 9,
    145, 1, 132, 6, 9,
    148, 0, 135, 6, 9,
    149, 0, 136, 6, 9,
    150, 1, 137, 6, 9,
    33, 3, 140, 6, 9,
    155, 2, 147, 6, 9,
    158, 1, 152, 6, 9,
    159, 1, 155, 6, 9,
    160, 1, 158, 6, 9,
    161, 1, 161, 6, 9,
    162, 1, 164, 6, 9,
    164, 3, 167, 6, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 11, 12, 13, 14,
    QMetaType::Void, QMetaType::QString, 16,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 16, 18, 19,

// slot: parameters
    QMetaType::Void, 0x80000000 | 42, 140,
    QMetaType::Void, 0x80000000 | 42, 142,
    QMetaType::Void, 0x80000000 | 42, 144,
    QMetaType::Void, 0x80000000 | 146, 147,
    QMetaType::Void,
    QMetaType::Void,
    QMetaType::Int, QMetaType::Int, 151,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, QMetaType::Int, 152, 153, 154,
    QMetaType::Int, QMetaType::Int, QMetaType::Int, 156, 157,
    QMetaType::Void, 0x80000000 | 42, 140,
    QMetaType::Void, 0x80000000 | 42, 142,
    QMetaType::Void, 0x80000000 | 42, 144,
    QMetaType::Void, 0x80000000 | 146, 147,
    QMetaType::Void, QMetaType::Int, 163,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, QMetaType::Int, 156, 157, 106,

 // properties: name, type, flags
    154, QMetaType::Int, 0x02005001, 		 // int BytesPerPixel
    153, QMetaType::Int, 0x02005001, 		 // int Height
    163, QMetaType::Int, 0x02015003, 		 // int ImageDataAddress
    152, QMetaType::Int, 0x02005001, 		 // int Width
    25, QMetaType::QString, 0x0a055003, 		 // QString control

    0 // eod
};

const QMetaObject IImageObject::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_DTControl__IImageObject, 0, 0, 0 }
};

void *IImageObject::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "DTControl::IImageObject"))
        return static_cast<void*>(const_cast<IImageObject*>(this));
    return QAxObject::qt_metacast(_clname);
}
static const uint qt_meta_data_DTControl__CDTDisplay[] = {

 // content:
    7, // revision
    166,  // classname
    2, 14, // classinfo
    22, 18, // methods
    14, 200, // properties
    0, 0, // enums/sets
    0, 0, // constructors
    0, // flags
    4, // signal count

 // classinfo: key, value
    1, 167, 
    3, 168, 

// signal: name, argc, parameters, tag, flags
    169, 3, 128, 6, 5,
    10, 4, 135, 6, 5,
    15, 1, 144, 6, 5,
    17, 3, 147, 6, 5,

// slot: name, argc, parameters, tag, flags
    32, 0, 154, 6, 9,
    171, 1, 155, 6, 9,
    33, 0, 158, 6, 9,
    173, 0, 159, 6, 9,
    174, 0, 160, 6, 9,
    175, 1, 161, 6, 9,
    176, 1, 164, 6, 9,
    178, 1, 167, 6, 9,
    180, 1, 170, 6, 9,
    182, 1, 173, 6, 9,
    184, 1, 176, 6, 9,
    186, 1, 179, 6, 9,
    188, 1, 182, 6, 9,
    190, 1, 185, 6, 9,
    192, 1, 188, 6, 9,
    194, 1, 191, 6, 9,
    196, 1, 194, 6, 9,
    198, 1, 197, 6, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::Int, QMetaType::Int, 156, 157, 170,
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 11, 12, 13, 14,
    QMetaType::Void, QMetaType::QString, 16,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 16, 18, 19,

// slot: parameters
    QMetaType::Void,
    QMetaType::Void, QMetaType::QString, 172,
    QMetaType::Int,
    QMetaType::Void,
    QMetaType::Void,
    QMetaType::Void, QMetaType::QString, 172,
    QMetaType::Void, 0x80000000 | 23, 177,
    QMetaType::Void, 0x80000000 | 23, 179,
    QMetaType::Void, QMetaType::Int, 181,
    QMetaType::Void, QMetaType::Double, 183,
    QMetaType::Void, QMetaType::UInt, 185,
    QMetaType::Void, QMetaType::UInt, 187,
    QMetaType::Void, QMetaType::Int, 189,
    QMetaType::Void, QMetaType::Int, 191,
    QMetaType::Void, QMetaType::Int, 193,
    QMetaType::Void, QMetaType::Int, 195,
    QMetaType::Void, QMetaType::Int, 197,
    QMetaType::Void, QMetaType::Int, 199,

 // properties: name, type, flags
    177, 0x80000000 | 23, 0x00015003, 		 // IUnknown* DataSource
    179, 0x80000000 | 23, 0x00015003, 		 // IUnknown* DisplayControl
    181, QMetaType::Int, 0x02015003, 		 // int DisplayScale
    183, QMetaType::Double, 0x06015003, 		 // double Gamma
    200, 0x80000000 | 23, 0x00005001, 		 // IUnknown* ImageObject
    185, QMetaType::UInt, 0x03015003, 		 // uint ImgHeight
    187, QMetaType::UInt, 0x03015003, 		 // uint ImgWidth
    189, QMetaType::Int, 0x02015003, 		 // int MapEnd
    191, QMetaType::Int, 0x02015003, 		 // int MapStart
    59, 0x80000000 | 23, 0x00005001, 		 // IUnknown* ObjectHandle
    193, QMetaType::Int, 0x02015003, 		 // int OrgPoint_X
    195, QMetaType::Int, 0x02015003, 		 // int OrgPoint_Y
    197, QMetaType::Int, 0x02015003, 		 // int RefreshMode
    199, QMetaType::Int, 0x02015003, 		 // int RefreshRate

    0 // eod
};

const QMetaObject CDTDisplay::staticMetaObject = {
{ &QWidget::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_DTControl__CDTDisplay, 0, 0, 0 }
};

void *CDTDisplay::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "DTControl::CDTDisplay"))
        return static_cast<void*>(const_cast<CDTDisplay*>(this));
    return QAxWidget::qt_metacast(_clname);
}
static const uint qt_meta_data_DTControl__IDTDisplay[] = {

 // content:
    7, // revision
    201,  // classname
    0, 0, // classinfo
    21, 14, // methods
    15, 184, // properties
    0, 0, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

// signal: name, argc, parameters, tag, flags
    10, 4, 119, 6, 5,
    15, 1, 128, 6, 5,
    17, 3, 131, 6, 5,

// slot: name, argc, parameters, tag, flags
    32, 0, 138, 6, 9,
    171, 1, 139, 6, 9,
    33, 0, 142, 6, 9,
    173, 0, 143, 6, 9,
    174, 0, 144, 6, 9,
    175, 1, 145, 6, 9,
    176, 1, 148, 6, 9,
    178, 1, 151, 6, 9,
    180, 1, 154, 6, 9,
    182, 1, 157, 6, 9,
    184, 1, 160, 6, 9,
    186, 1, 163, 6, 9,
    188, 1, 166, 6, 9,
    190, 1, 169, 6, 9,
    192, 1, 172, 6, 9,
    194, 1, 175, 6, 9,
    196, 1, 178, 6, 9,
    198, 1, 181, 6, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 11, 12, 13, 14,
    QMetaType::Void, QMetaType::QString, 16,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 16, 18, 19,

// slot: parameters
    QMetaType::Void,
    QMetaType::Void, QMetaType::QString, 172,
    QMetaType::Int,
    QMetaType::Void,
    QMetaType::Void,
    QMetaType::Void, QMetaType::QString, 172,
    QMetaType::Void, 0x80000000 | 23, 177,
    QMetaType::Void, 0x80000000 | 23, 179,
    QMetaType::Void, QMetaType::Int, 181,
    QMetaType::Void, QMetaType::Double, 183,
    QMetaType::Void, QMetaType::UInt, 185,
    QMetaType::Void, QMetaType::UInt, 187,
    QMetaType::Void, QMetaType::Int, 189,
    QMetaType::Void, QMetaType::Int, 191,
    QMetaType::Void, QMetaType::Int, 193,
    QMetaType::Void, QMetaType::Int, 195,
    QMetaType::Void, QMetaType::Int, 197,
    QMetaType::Void, QMetaType::Int, 199,

 // properties: name, type, flags
    177, 0x80000000 | 23, 0x00015003, 		 // IUnknown* DataSource
    179, 0x80000000 | 23, 0x00015003, 		 // IUnknown* DisplayControl
    181, QMetaType::Int, 0x02015003, 		 // int DisplayScale
    183, QMetaType::Double, 0x06015003, 		 // double Gamma
    200, 0x80000000 | 23, 0x00005001, 		 // IUnknown* ImageObject
    185, QMetaType::UInt, 0x03015003, 		 // uint ImgHeight
    187, QMetaType::UInt, 0x03015003, 		 // uint ImgWidth
    189, QMetaType::Int, 0x02015003, 		 // int MapEnd
    191, QMetaType::Int, 0x02015003, 		 // int MapStart
    59, 0x80000000 | 23, 0x00005001, 		 // IUnknown* ObjectHandle
    193, QMetaType::Int, 0x02015003, 		 // int OrgPoint_X
    195, QMetaType::Int, 0x02015003, 		 // int OrgPoint_Y
    197, QMetaType::Int, 0x02015003, 		 // int RefreshMode
    199, QMetaType::Int, 0x02015003, 		 // int RefreshRate
    25, QMetaType::QString, 0x0a055003, 		 // QString control

    0 // eod
};

const QMetaObject IDTDisplay::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_DTControl__IDTDisplay, 0, 0, 0 }
};

void *IDTDisplay::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "DTControl::IDTDisplay"))
        return static_cast<void*>(const_cast<IDTDisplay*>(this));
    return QAxObject::qt_metacast(_clname);
}
static const uint qt_meta_data_DTControl__CDTImage[] = {

 // content:
    7, // revision
    202,  // classname
    2, 14, // classinfo
    33, 18, // methods
    21, 294, // properties
    0, 0, // enums/sets
    0, 0, // constructors
    0, // flags
    7, // signal count

 // classinfo: key, value
    1, 203, 
    3, 204, 

// signal: name, argc, parameters, tag, flags
    29, 2, 183, 6, 5,
    205, 1, 188, 6, 5,
    207, 1, 191, 6, 5,
    209, 4, 194, 6, 5,
    10, 4, 203, 6, 5,
    15, 1, 212, 6, 5,
    17, 3, 215, 6, 5,

// slot: name, argc, parameters, tag, flags
    32, 0, 222, 6, 9,
    213, 0, 223, 6, 9,
    214, 0, 224, 6, 9,
    215, 1, 225, 6, 9,
    217, 1, 228, 6, 9,
    219, 0, 231, 6, 9,
    33, 0, 232, 6, 9,
    220, 3, 233, 6, 9,
    34, 2, 240, 6, 9,
    223, 1, 245, 6, 9,
    47, 1, 248, 6, 9,
    98, 1, 251, 6, 9,
    224, 1, 254, 6, 9,
    226, 1, 257, 6, 9,
    228, 1, 260, 6, 9,
    230, 1, 263, 6, 9,
    184, 1, 266, 6, 9,
    186, 1, 269, 6, 9,
    232, 1, 272, 6, 9,
    234, 1, 275, 6, 9,
    236, 1, 278, 6, 9,
    238, 1, 281, 6, 9,
    240, 1, 284, 6, 9,
    242, 1, 287, 6, 9,
    243, 0, 290, 6, 9,
    244, 1, 291, 6, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, 30, 31,
    QMetaType::Void, QMetaType::Int, 206,
    QMetaType::Void, QMetaType::Int, 208,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, 210, 211, 208, 212,
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 11, 12, 13, 14,
    QMetaType::Void, QMetaType::QString, 16,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 16, 18, 19,

// slot: parameters
    QMetaType::Void,
    QMetaType::Void,
    QMetaType::Void,
    QMetaType::Void, QMetaType::Int, 216,
    QMetaType::Int, QMetaType::Int, 218,
    QMetaType::Void,
    QMetaType::Int,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, 0x80000000 | 221, 152, 153, 222,
    QMetaType::Void, QMetaType::Int, 0x80000000 | 36, 35, 37,
    QMetaType::Void, QMetaType::Int, 154,
    QMetaType::Void, QMetaType::Int, 48,
    QMetaType::Void, 0x80000000 | 23, 99,
    QMetaType::Void, QMetaType::Int, 225,
    QMetaType::Void, QMetaType::Int, 227,
    QMetaType::Void, QMetaType::UInt, 229,
    QMetaType::Void, QMetaType::Int, 231,
    QMetaType::Void, QMetaType::Int, 185,
    QMetaType::Void, QMetaType::Int, 187,
    QMetaType::Void, QMetaType::UInt, 233,
    QMetaType::Void, QMetaType::UInt, 235,
    QMetaType::Void, QMetaType::Int, 237,
    QMetaType::Void, QMetaType::Int, 239,
    QMetaType::Void, QMetaType::Int, 241,
    QMetaType::Int, QMetaType::Int, 218,
    QMetaType::Void,
    QMetaType::Void, QMetaType::UInt, 245,

 // properties: name, type, flags
    246, QMetaType::Int, 0x02005001, 		 // int BandWidth
    154, QMetaType::Int, 0x02015003, 		 // int BytesPerPixel
    48, QMetaType::Int, 0x02015003, 		 // int ChannelType
    99, 0x80000000 | 23, 0x00015003, 		 // IUnknown* DetectorObject
    225, QMetaType::Int, 0x02015003, 		 // int DualScanMode
    227, QMetaType::Int, 0x02015003, 		 // int ExFrameTrigger
    229, QMetaType::UInt, 0x03015003, 		 // uint GainEnable
    200, 0x80000000 | 23, 0x00005001, 		 // IUnknown* ImageObject
    231, QMetaType::Int, 0x02015003, 		 // int ImagePort
    185, QMetaType::Int, 0x02015003, 		 // int ImgHeight
    187, QMetaType::Int, 0x02015003, 		 // int ImgWidth
    247, QMetaType::Int, 0x02005001, 		 // int IsGrabing
    57, QMetaType::Int, 0x02005001, 		 // int IsOpened
    58, QMetaType::Int, 0x02005001, 		 // int LastErrID
    59, 0x80000000 | 23, 0x00005001, 		 // IUnknown* ObjectHandle
    233, QMetaType::UInt, 0x03015003, 		 // uint OffsetEnable
    235, QMetaType::UInt, 0x03015003, 		 // uint PixelOrderEnable
    237, QMetaType::Int, 0x02015003, 		 // int Revert
    239, QMetaType::Int, 0x02015003, 		 // int SubFrameHeight
    241, QMetaType::Int, 0x02015003, 		 // int TimeOut
    245, QMetaType::UInt, 0x03015003, 		 // uint arrayCorrectionEnable

    0 // eod
};

const QMetaObject CDTImage::staticMetaObject = {
{ &QWidget::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_DTControl__CDTImage, 0, 0, 0 }
};

void *CDTImage::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "DTControl::CDTImage"))
        return static_cast<void*>(const_cast<CDTImage*>(this));
    return QAxWidget::qt_metacast(_clname);
}
static const uint qt_meta_data_DTControl__IDTImage[] = {

 // content:
    7, // revision
    248,  // classname
    0, 0, // classinfo
    29, 14, // methods
    22, 250, // properties
    0, 0, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

// signal: name, argc, parameters, tag, flags
    10, 4, 159, 6, 5,
    15, 1, 168, 6, 5,
    17, 3, 171, 6, 5,

// slot: name, argc, parameters, tag, flags
    32, 0, 178, 6, 9,
    213, 0, 179, 6, 9,
    214, 0, 180, 6, 9,
    215, 1, 181, 6, 9,
    217, 1, 184, 6, 9,
    219, 0, 187, 6, 9,
    33, 0, 188, 6, 9,
    220, 3, 189, 6, 9,
    34, 2, 196, 6, 9,
    223, 1, 201, 6, 9,
    47, 1, 204, 6, 9,
    98, 1, 207, 6, 9,
    224, 1, 210, 6, 9,
    226, 1, 213, 6, 9,
    228, 1, 216, 6, 9,
    230, 1, 219, 6, 9,
    184, 1, 222, 6, 9,
    186, 1, 225, 6, 9,
    232, 1, 228, 6, 9,
    234, 1, 231, 6, 9,
    236, 1, 234, 6, 9,
    238, 1, 237, 6, 9,
    240, 1, 240, 6, 9,
    242, 1, 243, 6, 9,
    243, 0, 246, 6, 9,
    244, 1, 247, 6, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 11, 12, 13, 14,
    QMetaType::Void, QMetaType::QString, 16,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 16, 18, 19,

// slot: parameters
    QMetaType::Void,
    QMetaType::Void,
    QMetaType::Void,
    QMetaType::Void, QMetaType::Int, 216,
    QMetaType::Int, QMetaType::Int, 218,
    QMetaType::Void,
    QMetaType::Int,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, 0x80000000 | 221, 152, 153, 222,
    QMetaType::Void, QMetaType::Int, 0x80000000 | 36, 35, 37,
    QMetaType::Void, QMetaType::Int, 154,
    QMetaType::Void, QMetaType::Int, 48,
    QMetaType::Void, 0x80000000 | 23, 99,
    QMetaType::Void, QMetaType::Int, 225,
    QMetaType::Void, QMetaType::Int, 227,
    QMetaType::Void, QMetaType::UInt, 229,
    QMetaType::Void, QMetaType::Int, 231,
    QMetaType::Void, QMetaType::Int, 185,
    QMetaType::Void, QMetaType::Int, 187,
    QMetaType::Void, QMetaType::UInt, 233,
    QMetaType::Void, QMetaType::UInt, 235,
    QMetaType::Void, QMetaType::Int, 237,
    QMetaType::Void, QMetaType::Int, 239,
    QMetaType::Void, QMetaType::Int, 241,
    QMetaType::Int, QMetaType::Int, 218,
    QMetaType::Void,
    QMetaType::Void, QMetaType::UInt, 245,

 // properties: name, type, flags
    246, QMetaType::Int, 0x02005001, 		 // int BandWidth
    154, QMetaType::Int, 0x02015003, 		 // int BytesPerPixel
    48, QMetaType::Int, 0x02015003, 		 // int ChannelType
    99, 0x80000000 | 23, 0x00015003, 		 // IUnknown* DetectorObject
    225, QMetaType::Int, 0x02015003, 		 // int DualScanMode
    227, QMetaType::Int, 0x02015003, 		 // int ExFrameTrigger
    229, QMetaType::UInt, 0x03015003, 		 // uint GainEnable
    200, 0x80000000 | 23, 0x00005001, 		 // IUnknown* ImageObject
    231, QMetaType::Int, 0x02015003, 		 // int ImagePort
    185, QMetaType::Int, 0x02015003, 		 // int ImgHeight
    187, QMetaType::Int, 0x02015003, 		 // int ImgWidth
    247, QMetaType::Int, 0x02005001, 		 // int IsGrabing
    57, QMetaType::Int, 0x02005001, 		 // int IsOpened
    58, QMetaType::Int, 0x02005001, 		 // int LastErrID
    59, 0x80000000 | 23, 0x00005001, 		 // IUnknown* ObjectHandle
    233, QMetaType::UInt, 0x03015003, 		 // uint OffsetEnable
    235, QMetaType::UInt, 0x03015003, 		 // uint PixelOrderEnable
    237, QMetaType::Int, 0x02015003, 		 // int Revert
    239, QMetaType::Int, 0x02015003, 		 // int SubFrameHeight
    241, QMetaType::Int, 0x02015003, 		 // int TimeOut
    245, QMetaType::UInt, 0x03015003, 		 // uint arrayCorrectionEnable
    25, QMetaType::QString, 0x0a055003, 		 // QString control

    0 // eod
};

const QMetaObject IDTImage::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_DTControl__IDTImage, 0, 0, 0 }
};

void *IDTImage::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "DTControl::IDTImage"))
        return static_cast<void*>(const_cast<IDTImage*>(this));
    return QAxObject::qt_metacast(_clname);
}

